import { GelatoFlavor } from "@/types/kitchen";

export const GELATO_SERIES = [
  "All",
  "Milk",
  "Chocolate",
  "Peanut & Nuts",
  "Fruit",
  "Dairy-Free",
  "Dessert",
  "Tea",
  "Coffee",
  "Seasonal",
] as const;

export const GELATO_FLAVORS: GelatoFlavor[] = [
  // 1. Milk Series (1-10)
  {
    id: "flv-milk-01",
    name: "Cookies & Cream",
    series: "Milk",
    description: "Creamy sweet milk base blended with dark chocolate cookies.",
    allergens: ["Milk", "Gluten"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-milk-02",
    name: "Sweet Cheese & Crispy Wafer",
    series: "Milk",
    description: "Sweet savory cheese gelato with crunchy wafer bites.",
    allergens: ["Milk", "Gluten"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-milk-03",
    name: "Cereal Milk & Honey Crunch",
    series: "Milk",
    description: "Toasted cereal milk flavor with honey clusters.",
    allergens: ["Milk", "Gluten"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-milk-04",
    name: "Korean Strawberry Milk",
    series: "Milk",
    description: "Creamy fresh milk with sweet strawberry jam swirl.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
    isBestSeller: true,
  },
  {
    id: "flv-milk-05",
    name: "Vanilla Stracciatella",
    series: "Milk",
    description: "Classic Italian vanilla bean base with dark chocolate flakes.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-milk-06",
    name: "Banana Nutella Swirl",
    series: "Milk",
    description: "Sweet banana milk base swirled with hazelnut cocoa spread.",
    allergens: ["Milk", "Nuts", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-milk-07",
    name: "Sweet Milk & Fudgy Brownies",
    series: "Milk",
    description: "Classic sweet milk with rich fudgy brownie chunks.",
    allergens: ["Milk", "Gluten", "Eggs"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-milk-08",
    name: "White Choco Crisp",
    series: "Milk",
    description: "Silky white chocolate milk with crispy wafer pearls.",
    allergens: ["Milk", "Gluten", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-milk-09",
    name: "Fior di Latte",
    series: "Milk",
    description: "Pure Italian sweet cream and whole milk gelato.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-milk-10",
    name: "Salted Caramel Sweet Cream",
    series: "Milk",
    description: "Rich sweet cream with swirls of housemade sea salt caramel.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },

  // 2. Chocolate Series (11-20)
  {
    id: "flv-choco-01",
    name: "Dark Chocolate",
    series: "Chocolate",
    description: "Pure rich dark chocolate gelato with intense cocoa flavor.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
    isBestSeller: true,
  },
  {
    id: "flv-choco-02",
    name: "Nutella Rocher",
    series: "Chocolate",
    description: "Hazelnut chocolate gelato with crispy praline crunch.",
    allergens: ["Milk", "Nuts", "Gluten", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-choco-03",
    name: "Choco Mint Flakes",
    series: "Chocolate",
    description: "Refreshing mint gelato with dark chocolate chips.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-choco-04",
    name: "Choco Brownie Chunk",
    series: "Chocolate",
    description: "Rich chocolate gelato stuffed with soft brownie chunks.",
    allergens: ["Milk", "Gluten", "Eggs"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-choco-05",
    name: "White Chocolate Berries",
    series: "Chocolate",
    description: "Sweet white chocolate with tangy raspberry ribbon.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-choco-06",
    name: "Choco Candied Orange",
    series: "Chocolate",
    description: "Dark chocolate with aromatic candied orange peel.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-choco-07",
    name: "Salted Caramel Choco Truffle",
    series: "Chocolate",
    description: "Dark chocolate with salted caramel swirl and truffle bites.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-choco-08",
    name: "Belgian Milk Chocolate",
    series: "Chocolate",
    description: "Smooth and creamy Belgian milk chocolate.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-choco-09",
    name: "Double Cocoa Fudge",
    series: "Chocolate",
    description: "Extra dark Dutch cocoa base with gooey chocolate fudge.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-choco-10",
    name: "Chocolate Marshmallow Crunch",
    series: "Chocolate",
    description: "Milk chocolate gelato with mini marshmallows and biscuit crumbs.",
    allergens: ["Milk", "Gluten", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },

  // 3. Peanut & Nuts Series (21-28)
  {
    id: "flv-nuts-01",
    name: "Pistachio Bronte",
    series: "Peanut & Nuts",
    description: "Authentic Italian Bronte pistachio gelato with nutty aroma.",
    allergens: ["Milk", "Nuts"],
    baseType: "milk",
    maxCapacityGram: 3000,
    isBestSeller: true,
  },
  {
    id: "flv-nuts-02",
    name: "Nocciola Piemonte",
    series: "Peanut & Nuts",
    description: "Roasted hazelnut from Piedmont Italy.",
    allergens: ["Milk", "Nuts"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-nuts-03",
    name: "Salted Peanut Butter Crisp",
    series: "Peanut & Nuts",
    description: "Savory salted peanut butter with caramelized nut bits.",
    allergens: ["Milk", "Peanuts"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-nuts-04",
    name: "Almond Butter & Caramel",
    series: "Peanut & Nuts",
    description: "Roasted almond butter base swirled with golden caramel.",
    allergens: ["Milk", "Nuts"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-nuts-05",
    name: "Kurogoma Black Sesame",
    series: "Peanut & Nuts",
    description: "Japanese toasted black sesame with earthy nutty notes.",
    allergens: ["Milk", "Sesame"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-nuts-06",
    name: "Pecan Maple Crunch",
    series: "Peanut & Nuts",
    description: "Butter pecan gelato with Canadian maple syrup ribbons.",
    allergens: ["Milk", "Nuts"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-nuts-07",
    name: "Macadamia White Velvet",
    series: "Peanut & Nuts",
    description: "Creamy macadamia nut gelato with white chocolate shavings.",
    allergens: ["Milk", "Nuts", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-nuts-08",
    name: "Cashew Honey Praline",
    series: "Peanut & Nuts",
    description: "Toasted cashew gelato swirled with honey blossom praline.",
    allergens: ["Milk", "Nuts"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },

  // 4. Fruit Series (29-37)
  {
    id: "flv-fruit-01",
    name: "Blueberry Cream Cheese",
    series: "Fruit",
    description: "Smooth cream cheese gelato swirled with blueberry jam.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-fruit-02",
    name: "Avocado Chocoloco",
    series: "Fruit",
    description: "Fresh butter avocado gelato swirled with dark chocolate sauce.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-fruit-03",
    name: "Raspberry Mascarpone",
    series: "Fruit",
    description: "Rich Italian mascarpone with fresh wild raspberry swirl.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-fruit-04",
    name: "Banana Cream Pie",
    series: "Fruit",
    description: "Ripe banana gelato with whipped cream and pie crust crumbs.",
    allergens: ["Milk", "Gluten"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-fruit-05",
    name: "Passionfruit Vanilla Bean",
    series: "Fruit",
    description: "Sweet vanilla bean gelato balanced with tart passionfruit pulp.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-fruit-06",
    name: "Peach & Honey Yogurt",
    series: "Fruit",
    description: "Greek yogurt gelato infused with yellow peach and wild honey.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-fruit-07",
    name: "Amarena Cherry Cream",
    series: "Fruit",
    description: "Sweet milk cream base infused with sour Italian Amarena cherries.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-fruit-08",
    name: "Mango Coconut Cream",
    series: "Fruit",
    description: "Sweet Alphonso mango gelato blended with rich coconut cream.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-fruit-09",
    name: "Strawberry Lemon Shortcake",
    series: "Fruit",
    description: "Sweet strawberry milk with lemon zest shortcake crumbles.",
    allergens: ["Milk", "Gluten"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },

  // 5. Dairy-Free / Sorbetto Series (38-46)
  {
    id: "flv-dairyfree-01",
    name: "Wild Mixed Berries Sorbet",
    series: "Dairy-Free",
    description: "Tangy sweet blend of strawberry, blueberry, and raspberry.",
    allergens: [],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
    isBestSeller: true,
  },
  {
    id: "flv-dairyfree-02",
    name: "Alphonso Mango Sorbetto",
    series: "Dairy-Free",
    description: "Silky pure tropical mango sorbet without dairy.",
    allergens: [],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
  },
  {
    id: "flv-dairyfree-03",
    name: "Midnight Dark Cocoa Sorbet",
    series: "Dairy-Free",
    description: "Intense dark cocoa water-based sorbet, 100% vegan.",
    allergens: ["Soy"],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
  },
  {
    id: "flv-dairyfree-04",
    name: "Dragonfruit Lime Pitaya",
    series: "Dairy-Free",
    description: "Red dragonfruit sorbet balanced with fresh lime juice.",
    allergens: [],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
  },
  {
    id: "flv-dairyfree-05",
    name: "Sicilian Limone Sorbetto",
    series: "Dairy-Free",
    description: "Refreshing lemon sorbet made with authentic Sicilian lemons.",
    allergens: [],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
  },
  {
    id: "flv-dairyfree-06",
    name: "Passionfruit Mint Freeze",
    series: "Dairy-Free",
    description: "Zesty passionfruit sorbet infused with crushed garden mint.",
    allergens: [],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
  },
  {
    id: "flv-dairyfree-07",
    name: "Lychee Raspberry Rose",
    series: "Dairy-Free",
    description: "Fragrant lychee sorbet swirled with raspberry rose water.",
    allergens: [],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
  },
  {
    id: "flv-dairyfree-08",
    name: "Pineapple Basil Sorbet",
    series: "Dairy-Free",
    description: "Sweet tropical pineapple sorbet infused with fresh basil.",
    allergens: [],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
  },
  {
    id: "flv-dairyfree-09",
    name: "Watermelon Mint Breeze",
    series: "Dairy-Free",
    description: "Crisp red watermelon sorbet with a hint of fresh mint.",
    allergens: [],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
  },

  // 6. Dessert Series (47-53)
  {
    id: "flv-dessert-01",
    name: "Signature Tiramisu",
    series: "Dessert",
    description: "Italian mascarpone, espresso savoiardi, cocoa powder.",
    allergens: ["Milk", "Gluten", "Eggs"],
    baseType: "milk",
    maxCapacityGram: 3000,
    isBestSeller: true,
  },
  {
    id: "flv-dessert-02",
    name: "Lotus Biscoff Speculoos",
    series: "Dessert",
    description: "Spiced caramel Biscoff gelato swirled with cookie spread.",
    allergens: ["Milk", "Gluten", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
    isBestSeller: true,
  },
  {
    id: "flv-dessert-03",
    name: "Caramelized Apple Pie",
    series: "Dessert",
    description: "Cinnamon apple gelato with buttery pie crust crumble.",
    allergens: ["Milk", "Gluten"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-dessert-04",
    name: "New York Cheese Cake",
    series: "Dessert",
    description: "Rich cream cheese gelato with graham cracker crust swirl.",
    allergens: ["Milk", "Gluten"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-dessert-05",
    name: "Dulce de Leche Churros",
    series: "Dessert",
    description: "Argentine caramel gelato swirled with cinnamon churro bites.",
    allergens: ["Milk", "Gluten"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-dessert-06",
    name: "Red Velvet Cream Cheese",
    series: "Dessert",
    description: "Cocoa red velvet cake gelato with cream cheese frosting.",
    allergens: ["Milk", "Gluten", "Eggs"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-dessert-07",
    name: "Panna Cotta Caramel",
    series: "Dessert",
    description: "Silky Italian vanilla panna cotta gelato with golden caramel.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },

  // 7. Tea Series (4 Varian Utama)
  {
    id: "flv-tea-01",
    name: "Kyoto Oici Matcha",
    series: "Tea",
    description: "Authentic premium Kyoto matcha green tea gelato.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
    isBestSeller: true,
  },
  {
    id: "flv-tea-02",
    name: "Earl Grey Lavender Milk",
    series: "Tea",
    description: "Bergamot infused Earl Grey milk tea with lavender floral notes.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-tea-03",
    name: "Jasmine Oolong Peach",
    series: "Tea",
    description: "Fragrant Jasmine Oolong tea swirled with yellow peach jam.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-tea-04",
    name: "Hojicha Roasted Green Tea",
    series: "Tea",
    description: "Toasted Japanese hojicha green tea with nutty caramel notes.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },

  // 8. Coffee Series (4 Varian Kekinian)
  {
    id: "flv-coffee-01",
    name: "Butterscotch Sea Salt Latte",
    series: "Coffee",
    description: "Rich butterscotch espresso gelato with sea salt cream.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
    isBestSeller: true,
  },
  {
    id: "flv-coffee-02",
    name: "Iced Caramel Macchiato Gelato",
    series: "Coffee",
    description: "Creamy espresso milk swirled with golden caramel drizzle.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-coffee-03",
    name: "Affogato Hazelnut Swirl",
    series: "Coffee",
    description: "Vanilla bean gelato soaked in dark espresso & hazelnut.",
    allergens: ["Milk", "Nuts"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-coffee-04",
    name: "Dirty Matcha Espresso",
    series: "Coffee",
    description: "Kyoto matcha gelato swirled with rich espresso shot.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },

  // 9. Seasonal Series (Hari Raya & Musim Special)
  {
    id: "flv-seasonal-01",
    name: "Gingerbread Spice & Molasses",
    series: "Seasonal",
    description: "Festive holiday gingerbread spice with molasses swirl.",
    allergens: ["Milk", "Gluten"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-seasonal-02",
    name: "Peppermint Bark Chocolate",
    series: "Seasonal",
    description: "Refreshing peppermint gelato with crushed candy cane & choco bark.",
    allergens: ["Milk", "Soy"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-seasonal-03",
    name: "Kastengel Cheese Swirl",
    series: "Seasonal",
    description: "Savory Edam cheese gelato with crunchy butter cookies.",
    allergens: ["Milk", "Gluten", "Eggs"],
    baseType: "milk",
    maxCapacityGram: 3000,
    isBestSeller: true,
  },
  {
    id: "flv-seasonal-04",
    name: "Nastar Pineapple Butter",
    series: "Seasonal",
    description: "Butter cookie gelato swirled with sweet caramelized pineapple jam.",
    allergens: ["Milk", "Gluten", "Eggs"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-seasonal-05",
    name: "Mandarin Orange Blossom",
    series: "Seasonal",
    description: "Sweet citrus mandarin sorbetto with gold orange blossoms.",
    allergens: [],
    baseType: "dairy-free",
    maxCapacityGram: 2500,
  },
  {
    id: "flv-seasonal-06",
    name: "Red Bean Lotus Pastry",
    series: "Seasonal",
    description: "Creamy sweet red bean gelato with lotus paste ribbon.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-seasonal-07",
    name: "Es Doger Deluxe",
    series: "Seasonal",
    description: "Indonesian Independence special: pink coconut milk with avocado & tape.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
  {
    id: "flv-seasonal-08",
    name: "Red White Coconut Strawberry",
    series: "Seasonal",
    description: "Layered coconut milk Fior di Latte & red strawberry sorbet.",
    allergens: ["Milk"],
    baseType: "milk",
    maxCapacityGram: 3000,
  },
];

export const GELATO_SERIES_META: Record<string, { badgeBg: string; badgeText: string; borderColor: string }> = {
  All: { badgeBg: "bg-slate-100", badgeText: "text-slate-700", borderColor: "border-slate-200" },
  Milk: { badgeBg: "bg-blue-50", badgeText: "text-blue-700", borderColor: "border-blue-200" },
  Chocolate: { badgeBg: "bg-amber-50", badgeText: "text-amber-900", borderColor: "border-amber-200" },
  "Peanut & Nuts": { badgeBg: "bg-orange-50", badgeText: "text-orange-800", borderColor: "border-orange-200" },
  Fruit: { badgeBg: "bg-rose-50", badgeText: "text-rose-700", borderColor: "border-rose-200" },
  "Dairy-Free": { badgeBg: "bg-emerald-50", badgeText: "text-emerald-700", borderColor: "border-emerald-200" },
  Dessert: { badgeBg: "bg-purple-50", badgeText: "text-purple-700", borderColor: "border-purple-200" },
  Tea: { badgeBg: "bg-teal-50", badgeText: "text-teal-700", borderColor: "border-teal-200" },
  Coffee: { badgeBg: "bg-stone-100", badgeText: "text-stone-800", borderColor: "border-stone-300" },
  Seasonal: { badgeBg: "bg-yellow-50", badgeText: "text-yellow-800", borderColor: "border-yellow-300" },
};
