-- ====================================================================
-- BLOC. GELATO ERP - PART 2: INITIAL DATA SEED DATA (EXACT 69 FLAVORS & FULL CATALOG)
-- Owner: Aldo Wijaya (own_aldo)
-- Date: 2026-09-15
-- ====================================================================

-- 1. SEED PROFILES (4 ROLES: cashier, kitchen, manager, owner)
INSERT INTO public.profiles (id, username, full_name, role, phone_number, pin_code, is_active)
VALUES
  ('a1b2c3d4-e5f6-4a1b-8c9d-0123456789ab', 'own_aldo', 'Aldo Wijaya', 'owner', '081234567890', '999999', true),
  ('b2c3d4e5-f6a1-4b2c-9d0e-1234567890bc', 'mngr_budi', 'Budi Santoso', 'manager', '081234567891', '888888', true),
  ('c3d4e5f6-a1b2-4c3d-0e1f-2345678901cd', 'ktch_chef', 'Chef Gelato', 'kitchen', '081234567892', '123456', true),
  ('d4e5f6a1-b2c3-4d4e-1f2a-3456789012de', 'cshr_siti', 'Siti Kasir', 'cashier', '081234567893', '111111', true)
ON CONFLICT (id) DO UPDATE 
SET full_name = EXCLUDED.full_name, pin_code = EXCLUDED.pin_code, role = EXCLUDED.role;

-- 2. SEED GELATO FLAVORS (EXACT 69 FLAVORS ACROSS 9 SERIES)
-- 2. SEED GELATO FLAVORS (EXACT 69 FLAVORS ACROSS 9 SERIES)
INSERT INTO public.gelato_flavors (id, name, series, description, allergens, base_type, max_capacity_gram, is_best_seller, is_seasonal)
VALUES
  ('flv-milk-01', 'Cookies & Cream', 'Milk', 'Fine cookie crumb blended into base mix during emulsification; coarse dark cookie chunks folded during extraction.', ARRAY['Milk','Gluten','Soy']::TEXT[], 'milk', 3000, true, false),
  ('flv-milk-02', 'Sweet Cheese & Crispy Wafer', 'Milk', 'Cream cheese emulsified into warm mix at 65°C; crispy wafer flakes folded during extraction.', ARRAY['Milk','Gluten','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-milk-03', 'Cereal Milk & Honey Crunch', 'Milk', 'Whole milk infused with toasted corn cereals (20 mins), strained and re-weighed. Honey crunch folded at extraction.', ARRAY['Milk','Gluten']::TEXT[], 'milk', 3000, true, false),
  ('flv-milk-04', 'Korean Strawberry Milk', 'Milk', 'Natural strawberry puree blended cold into aged base prior to churning; optional coulis swirl during extraction.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-milk-05', 'Vanilla Stracciatella', 'Milk', 'Premium single-origin vanilla caviar infused in dairy; melted dark chocolate couverture (65%) drizzled at -6°C during extraction.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-milk-06', 'Banana Nutella Swirl', 'Milk', 'Banana puree homogenized into cold base; warmed Nutella layered as continuous ribbon during pan fill.', ARRAY['Milk','Nuts','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-milk-07', 'Sweet Milk & Fudgy Brownies', 'Milk', 'Dense baked fudgy brownie chunks (chilled -18°C) folded during the final 30 seconds of churning.', ARRAY['Milk','Gluten','Eggs','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-milk-08', 'White Choco Crisp', 'Milk', 'Pure white chocolate (30% cocoa butter) melted into hot base at 60°C; crispy wafer pailletes folded at extraction.', ARRAY['Milk','Gluten','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-milk-09', 'Fior di Latte', 'Milk', 'Benchmark Italian milk flavor; zero added vanilla or extracts to showcase dairy purity.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-milk-10', 'Salted Caramel Sweet Cream', 'Milk', 'Sea salt caramel ribbon split 50% into warm base and 50% swirled into tub during extraction.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-choco-01', 'Dark Chocolate', 'Chocolate', 'Dark chocolate 70% melted at 50°C and emulsified into hot base; cocoa powder dry-blended with sugars.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, true, false),
  ('flv-choco-02', 'Nutella Rocher', 'Chocolate', 'Hazelnut cocoa paste melted into base; hazelnut praline crunch folded during extraction.', ARRAY['Milk','Nuts','Gluten','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-choco-03', 'Choco Mint Flakes', 'Chocolate', 'Natural spearmint / peppermint infusion in cold aged base; 65% dark chocolate stracciatella drizzled during extraction.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, true, false),
  ('flv-choco-04', 'Choco Brownie Chunk', 'Chocolate', 'Deep chocolate base with frozen brownie chunks layered in the pan at extraction.', ARRAY['Milk','Gluten','Eggs','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-choco-05', 'White Chocolate Berries', 'Chocolate', 'White chocolate melted into warm base at 60°C; raspberry coulis ribbon layered during pan fill.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-choco-06', 'Choco Candied Orange', 'Chocolate', 'Orange zest infused into hot base; artisanal candied orange peel bits folded at the end of extraction.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-choco-07', 'Salted Caramel Choco Truffle', 'Chocolate', 'Dark chocolate base paired with sea salt caramel ribbon and soft ganache truffle cubes.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-choco-08', 'Belgian Milk Chocolate', 'Chocolate', 'Belgian milk chocolate couverture (32% fat) melted into hot milk mix; sugar adjusted to accommodate chocolate sweetness.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-choco-09', 'Double Cocoa Fudge', 'Chocolate', 'Maximum cocoa mass formulation; finished with dense dark cocoa fudge ribbons layered during dispensing.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-choco-10', 'Chocolate Marshmallow Crunch', 'Chocolate', 'Dark chocolate base combined with mini marshmallows and cocoa rice crisps folded at the final rotation of churning.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-nuts-01', 'Pistachio Bronte', 'Peanut & Nuts', 'Pure 100% Bronte pistachio paste emulsified into warm dairy mix at 65°C; finished with fine sea salt.', ARRAY['Milk','Nuts']::TEXT[], 'milk', 3000, true, false),
  ('flv-nuts-02', 'Nocciola Piemonte', 'Peanut & Nuts', 'Piedmont IGP hazelnut paste mixed into hot base; matured 8 hours for full aromatic extraction.', ARRAY['Milk','Nuts']::TEXT[], 'milk', 3000, false, false),
  ('flv-nuts-03', 'Salted Peanut Butter Crisp', 'Peanut & Nuts', 'Pure roasted peanut paste emulsified into base; caramelized peanut crunch folded during extraction.', ARRAY['Milk','Peanuts','Gluten']::TEXT[], 'milk', 3000, true, false),
  ('flv-nuts-04', 'Almond Butter & Caramel', 'Peanut & Nuts', 'Roasted California almond butter blended with warm base; thick butter caramel ribbon swirled at pan fill.', ARRAY['Milk','Nuts']::TEXT[], 'milk', 3000, false, false),
  ('flv-nuts-05', 'Kurogoma Black Sesame', 'Peanut & Nuts', 'Deep-roasted Japanese black sesame paste blended at 70°C for intense earthy and nutty character.', ARRAY['Milk','Sesame']::TEXT[], 'milk', 3000, false, false),
  ('flv-nuts-06', 'Pecan Maple Crunch', 'Peanut & Nuts', 'Roasted pecan butter combined with pure maple syrup ribbons and candied pecan nuggets.', ARRAY['Milk','Nuts']::TEXT[], 'milk', 3000, false, false),
  ('flv-nuts-07', 'Macadamia White Velvet', 'Peanut & Nuts', 'Premium roasted macadamia paste with velvety white chocolate flakes folded gently during extraction.', ARRAY['Milk','Nuts','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-nuts-08', 'Cashew Honey Praline', 'Peanut & Nuts', 'Smooth cashew paste paired with organic wild blossom honey and crunchy cashew praline.', ARRAY['Milk','Nuts']::TEXT[], 'milk', 3000, false, false),
  ('flv-fruit-01', 'Blueberry Cream Cheese', 'Fruit', 'Cream cheese blended into hot base; wild blueberry reduction layered as ribbon during pan filling.', ARRAY['Milk']::TEXT[], 'milk', 3000, true, false),
  ('flv-fruit-02', 'Avocado Chocoloco', 'Fruit', 'Fresh ripe avocado puree blended cold immediately before churning; dark chocolate sauce swirled at extraction.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-fruit-03', 'Raspberry Mascarpone', 'Fruit', 'Italian mascarpone blended into base; seedless raspberry compote ribboned during extraction.', ARRAY['Milk']::TEXT[], 'milk', 3000, true, false),
  ('flv-fruit-04', 'Banana Cream Pie', 'Fruit', 'Ripe cavendish banana pureed into mix; butter graham crust crumbles added during extraction.', ARRAY['Milk','Gluten']::TEXT[], 'milk', 3000, false, false),
  ('flv-fruit-05', 'Passionfruit Vanilla Bean', 'Fruit', 'Tart passionfruit pulp blended with sweet vanilla cream base for vibrant tropical balance.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-fruit-06', 'Peach & Honey Yogurt', 'Fruit', 'Greek yogurt blended cold into mix with yellow peach puree and blossom honey.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-fruit-07', 'Amarena Cherry Cream', 'Fruit', 'Sweet Fior di Latte base swirled with tart whole Italian Amarena cherries in syrup.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-fruit-08', 'Mango Coconut Cream', 'Fruit', 'Rich coconut milk blended with fresh whole milk and sweet Alphonso mango puree.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-fruit-09', 'Strawberry Lemon Shortcake', 'Fruit', 'Strawberry milk base with fresh lemon zest and buttery shortcake crumble folded at extraction.', ARRAY['Milk','Gluten']::TEXT[], 'milk', 3000, false, false),
  ('flv-dairyfree-01', 'Wild Mixed Berries Sorbet', 'Dairy-Free', '100% water and fruit based. Cold-blended fruit puree with dry sugar-stabilizer mix before churning.', ARRAY[]::TEXT[], 'dairy-free', 2500, true, false),
  ('flv-dairyfree-02', 'Alphonso Mango Sorbetto', 'Dairy-Free', 'Premium Alphonso mango pulp blended with natural citrus juice and anti-freezing sugars.', ARRAY[]::TEXT[], 'dairy-free', 2500, false, false),
  ('flv-dairyfree-03', 'Midnight Dark Cocoa Sorbet', 'Dairy-Free', 'High-intensity Dutch cocoa powder boiled with mineral water to hydrate cocoa starches, then cooled before churning.', ARRAY['Soy']::TEXT[], 'dairy-free', 2500, true, false),
  ('flv-dairyfree-04', 'Dragonfruit Lime Pitaya', 'Dairy-Free', 'Vibrant red pitaya fruit puree paired with fresh lime juice for striking natural color and zesty tang.', ARRAY[]::TEXT[], 'dairy-free', 2500, false, false),
  ('flv-dairyfree-05', 'Sicilian Limone Sorbetto', 'Dairy-Free', 'Authentic Sicilian lemon juice balanced with higher anti-freezing sugars to prevent iciness.', ARRAY[]::TEXT[], 'dairy-free', 2500, false, false),
  ('flv-dairyfree-06', 'Passionfruit Mint Freeze', 'Dairy-Free', 'Seedless passionfruit puree infused with fresh garden mint leaves for a refreshing finish.', ARRAY[]::TEXT[], 'dairy-free', 2500, false, false),
  ('flv-dairyfree-07', 'Lychee Raspberry Rose', 'Dairy-Free', 'Sweet lychee pulp paired with wild raspberry puree and culinary rose water extract.', ARRAY[]::TEXT[], 'dairy-free', 2500, false, false),
  ('flv-dairyfree-08', 'Pineapple Basil Sorbet', 'Dairy-Free', 'Sweet tropical honey pineapple juice infused with fragrant Genovese fresh basil leaves.', ARRAY[]::TEXT[], 'dairy-free', 2500, false, false),
  ('flv-dairyfree-09', 'Watermelon Mint Breeze', 'Dairy-Free', 'Fresh pressed seedless red watermelon juice balanced with cooling mint essence.', ARRAY[]::TEXT[], 'dairy-free', 2500, false, false),
  ('flv-dessert-01', 'Signature Tiramisu', 'Dessert', 'Italian mascarpone base with espresso-soaked savoiardi sponge and Dutch cocoa dusting.', ARRAY['Milk','Gluten','Eggs']::TEXT[], 'milk', 3000, true, false),
  ('flv-dessert-02', 'Lotus Biscoff Speculoos', 'Dessert', 'Lotus Biscoff spread melted into warm mix; crunchy spiced speculoos biscuits folded at extraction.', ARRAY['Milk','Gluten','Soy']::TEXT[], 'milk', 3000, false, false),
  ('flv-dessert-03', 'Caramelized Apple Pie', 'Dessert', 'Spiced cinnamon apple compote layered with flaky buttery pie crust crumbs.', ARRAY['Milk','Gluten']::TEXT[], 'milk', 3000, true, false),
  ('flv-dessert-04', 'New York Cheese Cake', 'Dessert', 'Real Philadelphia style cream cheese emulsified into mix; golden graham cracker crust swirl folded during extraction.', ARRAY['Milk','Gluten']::TEXT[], 'milk', 3000, false, false),
  ('flv-dessert-05', 'Dulce de Leche Churros', 'Dessert', 'Argentine slow-cooked dulce de leche caramel base combined with crispy cinnamon sugar churro bites.', ARRAY['Milk','Gluten']::TEXT[], 'milk', 3000, false, false),
  ('flv-dessert-06', 'Red Velvet Cream Cheese', 'Dessert', 'Red velvet cocoa cake base swirled with tangy sweet cream cheese frosting ribbon.', ARRAY['Milk','Gluten','Eggs']::TEXT[], 'milk', 3000, false, false),
  ('flv-dessert-07', 'Panna Cotta Caramel', 'Dessert', 'Silky Italian sweet cream with Madagascar vanilla bean caviar and liquid amber caramel swirl.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-tea-01', 'Kyoto Oici Matcha', 'Tea', 'Ceremonial Uji matcha whisked into warm milk at 60°C; passed through a fine 200-mesh sieve.', ARRAY['Milk']::TEXT[], 'milk', 3000, true, false),
  ('flv-tea-02', 'Earl Grey Lavender Milk', 'Tea', 'Whole milk hot-infused with loose leaf Earl Grey tea for 25 minutes; culinary lavender essence added at cooling.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-tea-03', 'Jasmine Oolong Peach', 'Tea', 'Jasmine oolong tea milk infusion swirled with light yellow peach fruit ribbon.', ARRAY['Milk']::TEXT[], 'milk', 3000, true, false),
  ('flv-tea-04', 'Hojicha Roasted Green Tea', 'Tea', 'Deep roasted Shizuoka Hojicha powder micro-milled and blended into dairy base for nutty caramel notes.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-coffee-01', 'Butterscotch Sea Salt Latte', 'Coffee', 'Fresh espresso roast extract paired with housemade butterscotch paste and sea salt flakes.', ARRAY['Milk']::TEXT[], 'milk', 3000, true, false),
  ('flv-coffee-02', 'Iced Caramel Macchiato Gelato', 'Coffee', 'Freshly pulled double ristretto espresso blended with creamy milk and layered with caramel macchiato drizzle.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-coffee-03', 'Affogato Hazelnut Swirl', 'Coffee', 'Vanilla bean gelato base swirled with intense espresso concentrate and roasted hazelnut praline paste.', ARRAY['Milk','Nuts']::TEXT[], 'milk', 3000, true, false),
  ('flv-coffee-04', 'Dirty Matcha Espresso', 'Coffee', 'Uji matcha green tea gelato base with a rich dark espresso ristretto ribbon layered during pan dispensing.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, false),
  ('flv-seasonal-01', 'Gingerbread Spice & Molasses', 'Seasonal', 'Warm winter blend of ginger, cinnamon, and nutmeg with dark blackstrap molasses swirl.', ARRAY['Milk','Gluten']::TEXT[], 'milk', 3000, true, true),
  ('flv-seasonal-02', 'Peppermint Bark Chocolate', 'Seasonal', 'Cooling pure peppermint essential oil base folded with crunchy crushed candy canes and dark chocolate bark.', ARRAY['Milk','Soy']::TEXT[], 'milk', 3000, false, true),
  ('flv-seasonal-03', 'Kastengel Cheese Swirl', 'Seasonal', 'Finely grated aged Dutch Edam cheese melted into warm mix; crunchy butter kastengel cookies folded at extraction.', ARRAY['Milk','Gluten','Eggs']::TEXT[], 'milk', 3000, true, true),
  ('flv-seasonal-04', 'Nastar Pineapple Butter', 'Seasonal', 'Indonesian holiday classic: butter cookie gelato base swirled with caramelized clove-infused pineapple jam.', ARRAY['Milk','Gluten','Eggs']::TEXT[], 'milk', 3000, false, true),
  ('flv-seasonal-05', 'Mandarin Orange Blossom', 'Seasonal', 'Lunar New Year festive citrus sorbet made with sweet ponkan mandarin juice and fragrant orange blossom water.', ARRAY[]::TEXT[], 'dairy-free', 2500, false, true),
  ('flv-seasonal-06', 'Red Bean Lotus Pastry', 'Seasonal', 'Sweet Japanese Ogura red bean paste blended with milk base and swirled with lotus seed paste ribbon.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, true),
  ('flv-seasonal-07', 'Es Doger Deluxe', 'Seasonal', 'Indonesian Independence celebratory flavor: pink cocopandan coconut milk gelato with tape ketan hitam and avocado.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, true),
  ('flv-seasonal-08', 'Red White Coconut Strawberry', 'Seasonal', 'Merah Putih special: pure white coconut Fior di Latte layered with bright red strawberry coulis ribbon.', ARRAY['Milk']::TEXT[], 'milk', 3000, false, true)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  series = EXCLUDED.series,
  description = EXCLUDED.description,
  allergens = EXCLUDED.allergens,
  base_type = EXCLUDED.base_type,
  max_capacity_gram = EXCLUDED.max_capacity_gram,
  is_best_seller = EXCLUDED.is_best_seller,
  is_seasonal = EXCLUDED.is_seasonal;

-- 3. SEED SUPPLIERS
INSERT INTO public.suppliers (id, code, name, contact_person, phone, email, category, is_active)
VALUES
  ('sup-01', 'SUP-DAIRY-01', 'PT Diamond Cold Storage', 'Budi Dairy', '021-5551234', 'order@diamond.co.id', 'Dairy', true),
  ('sup-02', 'SUP-PACK-01', 'PT Packaging Nusantara', 'Siti Pack', '021-5555678', 'sales@packnus.id', 'Packaging', true),
  ('sup-03', 'SUP-FLAV-01', 'PT Agrisatwa Puree', 'Hendrik Puree', '021-5559012', 'info@agrisatwa.com', 'Flavor & Puree', true)
ON CONFLICT (id) DO NOTHING;

-- 4. SEED INVENTORY ITEMS (RAW MATERIALS, PACKAGING, TOPPINGS, SAUCES)
INSERT INTO public.inventory_items (id, item_code, item_name, category, current_stock, unit, min_restock_threshold, cost_per_unit, supplier_name)
VALUES
  ('pkg-piccolo', 'PKG-PIC', 'Small Cup 120ml (Piccolo)', 'packaging', 450, 'pcs', 100, 1500, 'PT Packaging Nusantara'),
  ('pkg-medio', 'PKG-MED', 'Medium Cup 200ml (Medio)', 'packaging', 320, 'pcs', 100, 2200, 'PT Packaging Nusantara'),
  ('pkg-grande', 'PKG-GRA', 'Large Cup 350ml (Grande)', 'packaging', 210, 'pcs', 50, 3500, 'PT Packaging Nusantara'),
  ('pkg-takeaway-500', 'PKG-TAK-500', 'Takeaway Tub 500g', 'packaging', 85, 'pcs', 30, 8500, 'PT Packaging Nusantara'),
  ('pkg-cone', 'PKG-CNE', 'Artisanal Waffle Cone', 'packaging', 280, 'pcs', 80, 1200, 'PT Packaging Nusantara'),
  ('top-choco-chips', 'TOP-CHK', 'Dark Choco Chips 60%', 'topping', 5500, 'gram', 1000, 45, 'PT Diamond Cold Storage'),
  ('top-roasted-hazelnut', 'TOP-HZL', 'Crushed Roasted Hazelnut', 'topping', 3200, 'gram', 800, 85, 'PT Agrisatwa Puree'),
  ('top-biscoff-crumb', 'TOP-BIS', 'Lotus Biscoff Biscuit Crumb', 'topping', 4100, 'gram', 1000, 35, 'PT Packaging Nusantara'),
  ('sauce-salted-caramel', 'SAC-CAR', 'Artisanal Salted Caramel Sauce', 'sauce', 4500, 'gram', 1000, 40, 'PT Diamond Cold Storage'),
  ('sauce-wild-berry', 'SAC-BER', 'Wild Berry Coulis Swirl', 'sauce', 3800, 'gram', 800, 50, 'PT Agrisatwa Puree'),
  ('inv-whole-milk-3-5-', 'RAW-WHOLE_MILK_3_5_', 'Whole Milk 3.5%', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dairy-cream-35-', 'RAW-DAIRY_CREAM_35_', 'Dairy Cream 35%', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-skim-milk-powder--smp-', 'RAW-SKIM_MILK_POWDER__SM', 'Skim Milk Powder (SMP)', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-sukrosa', 'RAW-SUKROSA', 'Sukrosa', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dextrose', 'RAW-DEXTROSE', 'Dextrose', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-glucose-powder-de40', 'RAW-GLUCOSE_POWDER_DE40', 'Glucose Powder DE40', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-invert-sugar', 'RAW-INVERT_SUGAR', 'Invert Sugar', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-base-5', 'RAW-BASE_5', 'Base 5', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-sorbet-stabilizer', 'RAW-SORBET_STABILIZER', 'Sorbet Stabilizer', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-soluble-fiber', 'RAW-SOLUBLE_FIBER', 'Soluble Fiber', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-cocoa-powder', 'RAW-COCOA_POWDER', 'Cocoa Powder', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dark-chocolate-70-75-', 'RAW-DARK_CHOCOLATE_70_75', 'Dark Chocolate 70-75%', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dark-chocolate-64-70-', 'RAW-DARK_CHOCOLATE_64_70', 'Dark Chocolate 64-70%', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-belgian-milk-chocolate', 'RAW-BELGIAN_MILK_CHOCOLA', 'Belgian Milk Chocolate', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-white-chocolate', 'RAW-WHITE_CHOCOLATE', 'White Chocolate', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-hazelnut-cocoa-spread', 'RAW-HAZELNUT_COCOA_SPREA', 'Hazelnut-Cocoa Spread', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-pistachio-bronte-paste', 'RAW-PISTACHIO_BRONTE_PAS', 'Pistachio Bronte Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-hazelnut-piemonte-paste', 'RAW-HAZELNUT_PIEMONTE_PA', 'Hazelnut Piemonte Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-peanut-butter', 'RAW-PEANUT_BUTTER', 'Peanut Butter', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-almond-butter', 'RAW-ALMOND_BUTTER', 'Almond Butter', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-kurogoma-black-sesame-paste', 'RAW-KUROGOMA_BLACK_SESAM', 'Kurogoma Black Sesame Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-macadamia-butter', 'RAW-MACADAMIA_BUTTER', 'Macadamia Butter', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-cashew-paste', 'RAW-CASHEW_PASTE', 'Cashew Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-strawberry-puree', 'RAW-STRAWBERRY_PUREE', 'Strawberry Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-blueberry-puree', 'RAW-BLUEBERRY_PUREE', 'Blueberry Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-raspberry-puree', 'RAW-RASPBERRY_PUREE', 'Raspberry Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-avocado-puree', 'RAW-AVOCADO_PUREE', 'Avocado Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-banana-puree', 'RAW-BANANA_PUREE', 'Banana Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-alphonso-mango-puree', 'RAW-ALPHONSO_MANGO_PUREE', 'Alphonso Mango Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-mixed-berry-puree', 'RAW-MIXED_BERRY_PUREE', 'Mixed Berry Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dragonfruit-puree', 'RAW-DRAGONFRUIT_PUREE', 'Dragonfruit Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lemon-juice', 'RAW-LEMON_JUICE', 'Lemon Juice', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-passionfruit-pulp', 'RAW-PASSIONFRUIT_PULP', 'Passionfruit Pulp', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-matcha-component', 'RAW-MATCHA_COMPONENT', 'Matcha Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-earl-grey-tea-component', 'RAW-EARL_GREY_TEA_COMPON', 'Earl Grey Tea Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-jasmine-oolong-tea-component', 'RAW-JASMINE_OOLONG_TEA_C', 'Jasmine Oolong Tea Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-hojicha-tea-component', 'RAW-HOJICHA_TEA_COMPONEN', 'Hojicha Tea Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-espresso-component', 'RAW-ESPRESSO_COMPONENT', 'Espresso Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-butterscotch-component', 'RAW-BUTTERSCOTCH_COMPONE', 'Butterscotch Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-caramel-component', 'RAW-CARAMEL_COMPONENT', 'Caramel Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-vanilla', 'RAW-VANILLA', 'Vanilla', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-sea-salt', 'RAW-SEA_SALT', 'Sea Salt', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-chocolate-sandwich-cookie-crumb', 'RAW-CHOCOLATE_SANDWICH_C', 'Chocolate Sandwich Cookie Crumb', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-crispy-wafer', 'RAW-CRISPY_WAFER', 'Crispy Wafer', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-toasted-cereal-component', 'RAW-TOASTED_CEREAL_COMPO', 'Toasted Cereal Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-honey-crunch', 'RAW-HONEY_CRUNCH', 'Honey Crunch', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-fudgy-brownie', 'RAW-FUDGY_BROWNIE', 'Fudgy Brownie', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-cream-cheese', 'RAW-CREAM_CHEESE', 'Cream Cheese', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-mascarpone', 'RAW-MASCARPONE', 'Mascarpone', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-molasses', 'RAW-MOLASSES', 'Molasses', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-gingerbread-spice-component', 'RAW-GINGERBREAD_SPICE_CO', 'Gingerbread Spice Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-gingerbread-biscuit-component', 'RAW-GINGERBREAD_BISCUIT_', 'Gingerbread Biscuit Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-kastengel-cheese-crumb', 'RAW-KASTENGEL_CHEESE_CRU', 'Kastengel Cheese Crumb', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-nastar-pineapple-jam', 'RAW-NASTAR_PINEAPPLE_JAM', 'Nastar Pineapple Jam', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-whole-milk-3-5---infused-', 'RAW-WHOLE_MILK_3_5___INF', 'Whole Milk 3.5% (Infused)', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-nutella---hazelnut-cocoa-spread', 'RAW-NUTELLA___HAZELNUT_C', 'Nutella / Hazelnut-Cocoa Spread', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-roasted-hazelnut-praline', 'RAW-ROASTED_HAZELNUT_PRA', 'Roasted Hazelnut Praline', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-crisped-wafer', 'RAW-CRISPED_WAFER', 'Crisped Wafer', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dark-chocolate--flakes-', 'RAW-DARK_CHOCOLATE__FLAK', 'Dark Chocolate (Flakes)', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-mint-infusion---component', 'RAW-MINT_INFUSION___COMP', 'Mint Infusion / Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dark-chocolate', 'RAW-DARK_CHOCOLATE', 'Dark Chocolate', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-fudgy-brownie-chunk', 'RAW-FUDGY_BROWNIE_CHUNK', 'Fudgy Brownie Chunk', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-berry-puree---swirl', 'RAW-BERRY_PUREE___SWIRL', 'Berry Puree / Swirl', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-candied-orange-peel', 'RAW-CANDIED_ORANGE_PEEL', 'Candied Orange Peel', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-orange-component---zest', 'RAW-ORANGE_COMPONENT___Z', 'Orange Component / Zest', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dark---milk-chocolate', 'RAW-DARK___MILK_CHOCOLAT', 'Dark / Milk Chocolate', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-marshmallow-component', 'RAW-MARSHMALLOW_COMPONEN', 'Marshmallow Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-peanut-crisp-component', 'RAW-PEANUT_CRISP_COMPONE', 'Peanut Crisp Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-almond-butter---paste', 'RAW-ALMOND_BUTTER___PAST', 'Almond Butter / Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-black-sesame-paste', 'RAW-BLACK_SESAME_PASTE', 'Black Sesame Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-pecan-paste', 'RAW-PECAN_PASTE', 'Pecan Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-maple-crunch-component', 'RAW-MAPLE_CRUNCH_COMPONE', 'Maple Crunch Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-macadamia-paste', 'RAW-MACADAMIA_PASTE', 'Macadamia Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-cashew-praline-component', 'RAW-CASHEW_PRALINE_COMPO', 'Cashew Praline Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-honey--madu-murni-', 'RAW-HONEY__MADU_MURNI_', 'Honey (Madu Murni)', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-vanilla-component', 'RAW-VANILLA_COMPONENT', 'Vanilla Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-pie---biscuit-component', 'RAW-PIE___BISCUIT_COMPON', 'Pie / Biscuit Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-passionfruit-puree', 'RAW-PASSIONFRUIT_PUREE', 'Passionfruit Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-vanilla-bean-component', 'RAW-VANILLA_BEAN_COMPONE', 'Vanilla Bean Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-vanilla-extract', 'RAW-VANILLA_EXTRACT', 'Vanilla Extract', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-yogurt', 'RAW-YOGURT', 'Yogurt', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-peach-puree', 'RAW-PEACH_PUREE', 'Peach Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-amarena-cherry-component', 'RAW-AMARENA_CHERRY_COMPO', 'Amarena Cherry Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-mango-puree', 'RAW-MANGO_PUREE', 'Mango Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-coconut-cream---milk', 'RAW-COCONUT_CREAM___MILK', 'Coconut Cream / Milk', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lemon-component', 'RAW-LEMON_COMPONENT', 'Lemon Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-shortcake---biscuit-component', 'RAW-SHORTCAKE___BISCUIT_', 'Shortcake / Biscuit Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-water', 'RAW-WATER', 'Water', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lemon-juice---acid-component', 'RAW-LEMON_JUICE___ACID_C', 'Lemon Juice / Acid Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-cocoa-powder--pure-dark-', 'RAW-COCOA_POWDER__PURE_D', 'Cocoa Powder (Pure Dark)', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-soluble-fiber---cocoa-solids', 'RAW-SOLUBLE_FIBER___COCO', 'Soluble Fiber / Cocoa Solids', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dragonfruit---pitaya-puree', 'RAW-DRAGONFRUIT___PITAYA', 'Dragonfruit / Pitaya Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lime-juice', 'RAW-LIME_JUICE', 'Lime Juice', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lemon-zest---aroma-component', 'RAW-LEMON_ZEST___AROMA_C', 'Lemon Zest / Aroma Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-mint-component', 'RAW-MINT_COMPONENT', 'Mint Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lemon---lime-juice', 'RAW-LEMON___LIME_JUICE', 'Lemon / Lime Juice', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lychee-puree', 'RAW-LYCHEE_PUREE', 'Lychee Puree', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-rose-component', 'RAW-ROSE_COMPONENT', 'Rose Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-pineapple-puree---juice', 'RAW-PINEAPPLE_PUREE___JU', 'Pineapple Puree / Juice', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-basil-component', 'RAW-BASIL_COMPONENT', 'Basil Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lemon---lime-component', 'RAW-LEMON___LIME_COMPONE', 'Lemon / Lime Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-watermelon-puree---juice', 'RAW-WATERMELON_PUREE___J', 'Watermelon Puree / Juice', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lime-component', 'RAW-LIME_COMPONENT', 'Lime Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lavender-component', 'RAW-LAVENDER_COMPONENT', 'Lavender Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-caramel-sauce---component', 'RAW-CARAMEL_SAUCE___COMP', 'Caramel Sauce / Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-hazelnut-paste', 'RAW-HAZELNUT_PASTE', 'Hazelnut Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-hazelnut---chocolate-swirl', 'RAW-HAZELNUT___CHOCOLATE', 'Hazelnut / Chocolate Swirl', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-dark-chocolate--bark---flakes-', 'RAW-DARK_CHOCOLATE__BARK', 'Dark Chocolate (Bark / Flakes)', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-peppermint-component', 'RAW-PEPPERMINT_COMPONENT', 'Peppermint Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-aged-cheese-component', 'RAW-AGED_CHEESE_COMPONEN', 'Aged Cheese Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-kastengel-crumb---swirl', 'RAW-KASTENGEL_CRUMB___SW', 'Kastengel Crumb / Swirl', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-pineapple-jam-component', 'RAW-PINEAPPLE_JAM_COMPON', 'Pineapple Jam Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-butter--mentega-murni-', 'RAW-BUTTER__MENTEGA_MURN', 'Butter (Mentega Murni)', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-nastar-crumb-component', 'RAW-NASTAR_CRUMB_COMPONE', 'Nastar Crumb Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-mandarin-puree---juice', 'RAW-MANDARIN_PUREE___JUI', 'Mandarin Puree / Juice', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-orange-blossom-component', 'RAW-ORANGE_BLOSSOM_COMPO', 'Orange Blossom Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-citrus-acid-component', 'RAW-CITRUS_ACID_COMPONEN', 'Citrus Acid Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-red-bean-paste', 'RAW-RED_BEAN_PASTE', 'Red Bean Paste', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lotus-pastry-component', 'RAW-LOTUS_PASTRY_COMPONE', 'Lotus Pastry Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-coconut-milk--santan-kental-', 'RAW-COCONUT_MILK__SANTAN', 'Coconut Milk (Santan Kental)', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-condensed-milk-component', 'RAW-CONDENSED_MILK_COMPO', 'Condensed Milk Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-red-bean-component', 'RAW-RED_BEAN_COMPONENT', 'Red Bean Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-fermented-cassava---tape', 'RAW-FERMENTED_CASSAVA___', 'Fermented Cassava / Tape', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-coconut-cream', 'RAW-COCONUT_CREAM', 'Coconut Cream', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-strawberry-swirl', 'RAW-STRAWBERRY_SWIRL', 'Strawberry Swirl', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lotus-biscoff-spread', 'RAW-LOTUS_BISCOFF_SPREAD', 'Lotus Biscoff Spread', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lotus-biscoff-crumb', 'RAW-LOTUS_BISCOFF_CRUMB', 'Lotus Biscoff Crumb', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-graham-cracker-crumb', 'RAW-GRAHAM_CRACKER_CRUMB', 'Graham Cracker Crumb', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-red-velvet-cake-crumb', 'RAW-RED_VELVET_CAKE_CRUM', 'Red Velvet Cake Crumb', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-apple-compote-component', 'RAW-APPLE_COMPOTE_COMPON', 'Apple Compote Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-pie-crust-crumb', 'RAW-PIE_CRUST_CRUMB', 'Pie Crust Crumb', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-cinnamon-powder', 'RAW-CINNAMON_POWDER', 'Cinnamon Powder', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-key-lime-juice-component', 'RAW-KEY_LIME_JUICE_COMPO', 'Key Lime Juice Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-lemon-curd-component', 'RAW-LEMON_CURD_COMPONENT', 'Lemon Curd Component', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-marshmallow-meringue-swirl', 'RAW-MARSHMALLOW_MERINGUE', 'Marshmallow Meringue Swirl', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage'),
  ('inv-tart-pastry-crumb', 'RAW-TART_PASTRY_CRUMB', 'Tart Pastry Crumb', 'raw_material', 25000, 'gram', 5000, 25, 'PT Diamond Cold Storage')
ON CONFLICT (id) DO UPDATE SET current_stock = EXCLUDED.current_stock;

-- 5. SEED 54 SHOWCASE DISPLAY SLOTS (FREEZER A, B, C x 18 SLOTS)
INSERT INTO public.showcase_slots (id, freezer_group, slot_number, flavor_id, flavor_name, series, base_type, max_capacity_gram, current_grams, days_open, max_days_allowed, status)
VALUES
  ('slot-a-01', 'A', 1, 'flv-milk-01', 'COOKIES & CREAM', 'Milk Series', 'milk', 3000, 2674, 2, 8, 'NORMAL'),
  ('slot-a-02', 'A', 2, 'flv-milk-02', 'SWEET CHEESE & CRISPY WAFER', 'Milk Series', 'milk', 3000, 2504, 2, 8, 'NORMAL'),
  ('slot-a-03', 'A', 3, 'flv-milk-03', 'CEREAL MILK & HONEY CRUNCH', 'Milk Series', 'milk', 3000, 2432, 2, 8, 'NORMAL'),
  ('slot-a-04', 'A', 4, 'flv-milk-04', 'KOREAN STRAWBERRY MILK', 'Milk Series', 'milk', 3000, 2704, 2, 8, 'NORMAL'),
  ('slot-a-05', 'A', 5, 'flv-milk-05', 'VANILLA STRACCIATELLA', 'Milk Series', 'milk', 3000, 2125, 2, 8, 'NORMAL'),
  ('slot-a-06', 'A', 6, 'flv-milk-06', 'BANANA NUTELLA SWIRL', 'Milk Series', 'milk', 3000, 2655, 2, 8, 'NORMAL'),
  ('slot-a-07', 'A', 7, 'flv-milk-07', 'SWEET MILK & FUDGY BROWNIES', 'Milk Series', 'milk', 3000, 2397, 2, 8, 'NORMAL'),
  ('slot-a-08', 'A', 8, 'flv-milk-08', 'WHITE CHOCO CRISP', 'Milk Series', 'milk', 3000, 2759, 2, 8, 'NORMAL'),
  ('slot-a-09', 'A', 9, 'flv-milk-09', 'FIOR DI LATTE', 'Milk Series', 'milk', 3000, 2257, 2, 8, 'NORMAL'),
  ('slot-a-10', 'A', 10, 'flv-milk-10', 'SALTED CARAMEL SWEET CREAM', 'Milk Series', 'milk', 3000, 2228, 2, 8, 'NORMAL'),
  ('slot-a-11', 'A', 11, 'flv-choco-01', 'DARK CHOCOLATE', 'Chocolate Series', 'milk', 3000, 2652, 2, 8, 'NORMAL'),
  ('slot-a-12', 'A', 12, 'flv-choco-02', 'NUTELLA ROCHER', 'Chocolate Series', 'milk', 3000, 2447, 2, 8, 'NORMAL'),
  ('slot-a-13', 'A', 13, 'flv-choco-03', 'CHOCO MINT FLAKES', 'Chocolate Series', 'milk', 3000, 2648, 2, 8, 'NORMAL'),
  ('slot-a-14', 'A', 14, 'flv-choco-04', 'CHOCO BROWNIE CHUNK', 'Chocolate Series', 'milk', 3000, 2517, 2, 8, 'NORMAL'),
  ('slot-a-15', 'A', 15, 'flv-choco-05', 'WHITE CHOCOLATE BERRIES', 'Chocolate Series', 'milk', 3000, 2699, 2, 8, 'NORMAL'),
  ('slot-a-16', 'A', 16, 'flv-choco-06', 'CHOCO CANDIED ORANGE', 'Chocolate Series', 'milk', 3000, 2681, 2, 8, 'NORMAL'),
  ('slot-a-17', 'A', 17, 'flv-choco-07', 'SALTED CARAMEL CHOCO TRUFFLE', 'Chocolate Series', 'milk', 3000, 2191, 2, 8, 'NORMAL'),
  ('slot-a-18', 'A', 18, 'flv-choco-08', 'BELGIAN MILK CHOCOLATE', 'Chocolate Series', 'milk', 3000, 2271, 2, 8, 'NORMAL'),
  ('slot-b-01', 'B', 1, 'flv-choco-09', 'DOUBLE COCOA FUDGE', 'Chocolate Series', 'milk', 3000, 2263, 2, 8, 'NORMAL'),
  ('slot-b-02', 'B', 2, 'flv-choco-10', 'CHOCOLATE MARSHMALLOW CRUNCH', 'Chocolate Series', 'milk', 3000, 2243, 2, 8, 'NORMAL'),
  ('slot-b-03', 'B', 3, 'flv-nuts-01', 'PISTACHIO BRONTE', 'Peanut & Nuts Series', 'milk', 3000, 2721, 2, 8, 'NORMAL'),
  ('slot-b-04', 'B', 4, 'flv-nuts-02', 'NOCCIOLA PIEMONTE', 'Peanut & Nuts Series', 'milk', 3000, 2133, 2, 8, 'NORMAL'),
  ('slot-b-05', 'B', 5, 'flv-nuts-03', 'SALTED PEANUT BUTTER CRISP', 'Peanut & Nuts Series', 'milk', 3000, 2696, 2, 8, 'NORMAL'),
  ('slot-b-06', 'B', 6, 'flv-nuts-04', 'ALMOND BUTTER & CARAMEL', 'Peanut & Nuts Series', 'milk', 3000, 2683, 2, 8, 'NORMAL'),
  ('slot-b-07', 'B', 7, 'flv-nuts-05', 'KUROGOMA BLACK SESAME', 'Peanut & Nuts Series', 'milk', 3000, 2300, 2, 8, 'NORMAL'),
  ('slot-b-08', 'B', 8, 'flv-nuts-06', 'PECAN MAPLE CRUNCH', 'Peanut & Nuts Series', 'milk', 3000, 2246, 2, 8, 'NORMAL'),
  ('slot-b-09', 'B', 9, 'flv-nuts-07', 'MACADAMIA WHITE VELVET', 'Peanut & Nuts Series', 'milk', 3000, 2117, 2, 8, 'NORMAL'),
  ('slot-b-10', 'B', 10, 'flv-nuts-08', 'CASHEW HONEY PRALINE', 'Peanut & Nuts Series', 'milk', 3000, 2301, 2, 8, 'NORMAL'),
  ('slot-b-11', 'B', 11, 'flv-fruit-01', 'BLUEBERRY CREAM CHEESE', 'Fruit Series', 'milk', 3000, 2680, 2, 8, 'NORMAL'),
  ('slot-b-12', 'B', 12, 'flv-fruit-02', 'AVOCADO CHOCOLOCO', 'Fruit Series', 'milk', 3000, 2011, 2, 8, 'NORMAL'),
  ('slot-b-13', 'B', 13, 'flv-fruit-03', 'RASPBERRY MASCARPONE', 'Fruit Series', 'milk', 3000, 2370, 2, 8, 'NORMAL'),
  ('slot-b-14', 'B', 14, 'flv-fruit-04', 'BANANA CREAM PIE', 'Fruit Series', 'milk', 3000, 2681, 2, 8, 'NORMAL'),
  ('slot-b-15', 'B', 15, 'flv-fruit-05', 'PASSIONFRUIT VANILLA BEAN', 'Fruit Series', 'milk', 3000, 2672, 2, 8, 'NORMAL'),
  ('slot-b-16', 'B', 16, 'flv-fruit-06', 'PEACH & HONEY YOGURT', 'Fruit Series', 'milk', 3000, 2250, 2, 8, 'NORMAL'),
  ('slot-b-17', 'B', 17, 'flv-fruit-07', 'AMARENA CHERRY CREAM', 'Fruit Series', 'milk', 3000, 2775, 2, 8, 'NORMAL'),
  ('slot-b-18', 'B', 18, 'flv-fruit-08', 'MANGO COCONUT CREAM', 'Fruit Series', 'milk', 3000, 2567, 2, 8, 'NORMAL'),
  ('slot-c-01', 'C', 1, 'flv-fruit-09', 'STRAWBERRY LEMON SHORTCAKE', 'Fruit Series', 'milk', 3000, 2362, 2, 8, 'NORMAL'),
  ('slot-c-02', 'C', 2, 'flv-dairyfree-01', 'WILD MIXED BERRIES SORBET', 'Dairy-Free / Sorbetto Series', 'dairy-free', 2500, 2278, 2, 8, 'NORMAL'),
  ('slot-c-03', 'C', 3, 'flv-dairyfree-02', 'ALPHONSO MANGO SORBETTO', 'Dairy-Free / Sorbetto Series', 'dairy-free', 2500, 2374, 2, 8, 'NORMAL'),
  ('slot-c-04', 'C', 4, 'flv-dairyfree-03', 'MIDNIGHT DARK COCOA SORBET', 'Dairy-Free / Sorbetto Series', 'dairy-free', 2500, 2702, 2, 8, 'NORMAL'),
  ('slot-c-05', 'C', 5, 'flv-dairyfree-04', 'DRAGONFRUIT LIME PITAYA', 'Dairy-Free / Sorbetto Series', 'dairy-free', 2500, 2621, 2, 8, 'NORMAL'),
  ('slot-c-06', 'C', 6, 'flv-dairyfree-05', 'SICILIAN LIMONE SORBETTO', 'Dairy-Free / Sorbetto Series', 'dairy-free', 2500, 2349, 2, 8, 'NORMAL'),
  ('slot-c-07', 'C', 7, 'flv-dairyfree-06', 'PASSIONFRUIT MINT FREEZE', 'Dairy-Free / Sorbetto Series', 'dairy-free', 2500, 2618, 2, 8, 'NORMAL'),
  ('slot-c-08', 'C', 8, 'flv-dairyfree-07', 'LYCHEE RASPBERRY ROSE', 'Dairy-Free / Sorbetto Series', 'dairy-free', 2500, 2584, 2, 8, 'NORMAL'),
  ('slot-c-09', 'C', 9, 'flv-dairyfree-08', 'PINEAPPLE BASIL SORBET', 'Dairy-Free / Sorbetto Series', 'dairy-free', 2500, 2336, 2, 8, 'NORMAL'),
  ('slot-c-10', 'C', 10, 'flv-dairyfree-09', 'WATERMELON MINT BREEZE', 'Dairy-Free / Sorbetto Series', 'dairy-free', 2500, 2295, 2, 8, 'NORMAL'),
  ('slot-c-11', 'C', 11, 'flv-tea-01', 'KYOTO OICI MATCHA', 'Tea Series', 'milk', 3000, 2730, 2, 8, 'NORMAL'),
  ('slot-c-12', 'C', 12, 'flv-tea-02', 'EARL GREY LAVENDER MILK', 'Tea Series', 'milk', 3000, 2435, 2, 8, 'NORMAL'),
  ('slot-c-13', 'C', 13, 'flv-tea-03', 'JASMINE OOLONG PEACH', 'Tea Series', 'milk', 3000, 2359, 2, 8, 'NORMAL'),
  ('slot-c-14', 'C', 14, 'flv-tea-04', 'HOJICHA ROASTED GREEN TEA', 'Tea Series', 'milk', 3000, 2113, 2, 8, 'NORMAL'),
  ('slot-c-15', 'C', 15, 'flv-coffee-01', 'BUTTERSCOTCH SEA SALT LATTE', 'Coffee Series', 'milk', 3000, 2344, 2, 8, 'NORMAL'),
  ('slot-c-16', 'C', 16, 'flv-coffee-02', 'ICED CARAMEL MACCHIATO GELATO', 'Coffee Series', 'milk', 3000, 2173, 2, 8, 'NORMAL'),
  ('slot-c-17', 'C', 17, 'flv-coffee-03', 'AFFOGATO HAZELNUT SWIRL', 'Coffee Series', 'milk', 3000, 2110, 2, 8, 'NORMAL'),
  ('slot-c-18', 'C', 18, 'flv-coffee-04', 'DIRTY MATCHA ESPRESSO', 'Coffee Series', 'milk', 3000, 2568, 2, 8, 'NORMAL')
ON CONFLICT (id) DO UPDATE SET flavor_name = EXCLUDED.flavor_name;

-- 6. SEED MEMBERS
INSERT INTO public.members (id, member_code, full_name, phone_number, tier, loyalty_points, total_spent)
VALUES
  ('mbr-01', 'MBR-8801', 'Hendra Wijaya', '081809091122', 'Gold', 450, 2450000),
  ('mbr-02', 'MBR-8802', 'Dewi Lestari', '081299887766', 'Silver', 120, 680000)
ON CONFLICT (id) DO NOTHING;
