-- ====================================================================
-- BLOC. GELATO ERP - PART 3: MASTER BOM RECIPES SEED DATA (EXACT 69 FLAVORS, 9 SERIES)
-- Populate recipes & recipe_ingredients for EXACT 69 GELATO FLAVORS from BOM documentation
-- Date: 2026-09-15
-- ====================================================================

-- 1. SEED RECIPES HEADERS FOR ALL 69 FLAVORS
INSERT INTO public.recipes (id, flavor_id, flavor_name, series, base_yield_liter, churning_time_minutes, target_overrun_percent, instructions)
VALUES
  ('rcp-milk-01', 'flv-milk-01', 'COOKIES & CREAM', 'Milk Series', 5, 15, 35, '[Master Base: Fior di Latte / White Milk Base] Fine crumb masuk saat blending base
ON CONFLICT (id) DO UPDATE SET
  flavor_name = EXCLUDED.flavor_name,
  instructions = EXCLUDED.instructions; coarse crumb masuk sebagai inclusion menjelang akhir churning.'),
  ('rcp-milk-02', 'flv-milk-02', 'SWEET CHEESE & CRISPY WAFER', 'Milk Series', 5, 15, 35, '[Master Base: Cream Cheese / Mascarpone Base (Adjusted Milk Base)] Cream cheese diemulsikan ke base mix; crispy wafer dimasukkan sebagai inclusion pada akhir churning.'),
  ('rcp-milk-03', 'flv-milk-03', 'CEREAL MILK & HONEY CRUNCH', 'Milk Series', 5, 15, 35, '[Master Base: Fior di Latte / White Milk Base] Susu diinfusikan dengan toasted cereal, disaring, dan ditimbang kembali sebelum balancing. Honey crunch masuk akhir churning.'),
  ('rcp-milk-04', 'flv-milk-04', 'KOREAN STRAWBERRY MILK', 'Milk Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Puree strawberry asli dicampur ke dalam mix balancing; sebagian dapat dialokasikan sebagai coulis/swirl saat extraction.'),
  ('rcp-milk-05', 'flv-milk-05', 'VANILLA STRACCIATELLA', 'Milk Series', 5, 15, 35, '[Master Base: Fior di Latte / White Milk Base] Cokelat leleh (64–70%) di-drizzle tipis saat penarikan gelato dari mesin churning sehingga membeku membentuk serpihan renyah.'),
  ('rcp-milk-06', 'flv-milk-06', 'BANANA NUTELLA SWIRL', 'Milk Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Banana puree dihomogenisasi bersama base mix; Nutella / Hazelnut spread dimasukkan sebagai layer swirl saat dispensing ke pan.'),
  ('rcp-milk-07', 'flv-milk-07', 'SWEET MILK & FUDGY BROWNIES', 'Milk Series', 5, 15, 35, '[Master Base: Fior di Latte / White Milk Base] Fudgy brownie dipotong dadu kecil (low moisture), dimasukkan sebagai inclusion pada akhir churning.'),
  ('rcp-milk-08', 'flv-milk-08', 'WHITE CHOCO CRISP', 'Milk Series', 5, 15, 35, '[Master Base: Fior di Latte / White Milk Base] White chocolate dilelehkan dan diemulsikan saat pasteurisasi base; crispy wafer dimasukkan di akhir churning agar renyah terjaga.'),
  ('rcp-milk-09', 'flv-milk-09', 'FIOR DI LATTE', 'Milk Series', 5, 15, 35, '[Master Base: Fior di Latte / White Milk Base (Benchmark Flavor)] Tanpa penambahan vanilla atau perisa artifisial; menonjolkan kemurnian rasa susu segar dan dairy cream.'),
  ('rcp-milk-10', 'flv-milk-10', 'SALTED CARAMEL SWEET CREAM', 'Milk Series', 5, 15, 35, '[Master Base: Fior di Latte / White Milk Base] Caramel component dimasak terpisah lalu diemulsikan ke base mix dan/atau dialokasikan sebagian sebagai ribbon swirl.'),
  ('rcp-choco-01', 'flv-choco-01', 'DARK CHOCOLATE', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base] Dark chocolate (70–75%) dilelehkan dan diemulsikan saat balancing. Cocoa powder dicampur bersama dry ingredients.'),
  ('rcp-choco-02', 'flv-choco-02', 'NUTELLA ROCHER', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base] Hazelnut-cocoa spread masuk ke base mix; roasted hazelnut praline dan crisped wafer masuk sebagai inclusion di akhir churning.'),
  ('rcp-choco-03', 'flv-choco-03', 'CHOCO MINT FLAKES', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base] Mint component dicampur ke base; lelehan dark chocolate di-drizzle secara stracciatella saat extraction menghasilkan flakes tipis.'),
  ('rcp-choco-04', 'flv-choco-04', 'CHOCO BROWNIE CHUNK', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base] Cokelat dan cocoa powder masuk base mix; fudgy brownie chunk masuk sebagai inclusion padat pada akhir tahap churning.'),
  ('rcp-choco-05', 'flv-choco-05', 'WHITE CHOCOLATE BERRIES', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base (White Chocolate Matrix)] White chocolate dilelehkan dan diemulsikan pada base mix; berry puree/compote diaplikasikan sebagai swirl layer saat dispensing.'),
  ('rcp-choco-06', 'flv-choco-06', 'CHOCO CANDIED ORANGE', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base] Dark chocolate, cocoa, & orange zest/extract dihomogenisasi ke base; candied orange peel dimasukkan di akhir churning.'),
  ('rcp-choco-07', 'flv-choco-07', 'SALTED CARAMEL CHOCO TRUFFLE', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base] Cokelat dan cocoa di-emulsi ke base; caramel component dan chocolate truffle dimasukkan sebagai swirl & inclusion.'),
  ('rcp-choco-08', 'flv-choco-08', 'BELGIAN MILK CHOCOLATE', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base (Milk Chocolate Matrix)] Belgian milk chocolate dilelehkan dan dicampurkan saat balancing. Gula sukrosa diturunkan untuk mengimbangi gula dari couverture.'),
  ('rcp-choco-09', 'flv-choco-09', 'DOUBLE COCOA FUDGE', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base (High Cocoa Solids)] Kombinasi cocoa solids tinggi pada base mix; fudge component ditambahkan sebagai ribbon swirl pekat saat extraction.'),
  ('rcp-choco-10', 'flv-choco-10', 'CHOCOLATE MARSHMALLOW CRUNCH', 'Chocolate Series', 5, 15, 35, '[Master Base: Chocolate Base] Base cokelat intens; marshmallow dan crunch component dimasukkan pada tahap akhir churning atau folding saat penarikan ke pan.'),
  ('rcp-nuts-01', 'flv-nuts-01', 'PISTACHIO BRONTE', 'Peanut & Nuts Series', 5, 15, 35, '[Master Base: Nut Base] Pistachio Bronte paste dihomogenisasi saat blending base agar emulsi lemak nabati menyatu stabil; tanpa pewarna sintetis tambahan.'),
  ('rcp-nuts-02', 'flv-nuts-02', 'NOCCIOLA PIEMONTE', 'Peanut & Nuts Series', 5, 15, 35, '[Master Base: Nut Base] Hazelnut Piemonte paste dicampurkan pada tahap awal pasteurisasi untuk ekstraksi aroma roasted hazelnut yang maksimal.'),
  ('rcp-nuts-03', 'flv-nuts-03', 'SALTED PEANUT BUTTER CRISP', 'Peanut & Nuts Series', 5, 15, 35, '[Master Base: Nut Base] Peanut butter diemulsikan ke base; peanut crisp dimasukkan sebagai inclusion pada tahap akhir churning.'),
  ('rcp-nuts-04', 'flv-nuts-04', 'ALMOND BUTTER & CARAMEL', 'Peanut & Nuts Series', 5, 15, 35, '[Master Base: Nut Base] Almond butter dihomogenisasi ke dalam base mix; caramel component diaplikasikan sebagai ribbon swirl saat penarikan gelato.'),
  ('rcp-nuts-05', 'flv-nuts-05', 'KUROGOMA BLACK SESAME', 'Peanut & Nuts Series', 5, 15, 35, '[Master Base: Nut Base (Seed Matrix)] Roasted black sesame paste dicampurkan saat balancing base; profil rasa nutty dengan sentuhan savory dan aroma wijen hitam panggang.'),
  ('rcp-nuts-06', 'flv-nuts-06', 'PECAN MAPLE CRUNCH', 'Peanut & Nuts Series', 5, 15, 35, '[Master Base: Nut Base] Toasted pecan paste diemulsikan ke base; maple crunch component dimasukkan pada akhir proses churning sebagai tekstur renyah.'),
  ('rcp-nuts-07', 'flv-nuts-07', 'MACADAMIA WHITE VELVET', 'Peanut & Nuts Series', 5, 15, 35, '[Master Base: Nut Base] Macadamia paste dan white chocolate leleh diemulsikan ke base mix saat proses pasteurisasi untuk menghasilkan tekstur velvet.'),
  ('rcp-nuts-08', 'flv-nuts-08', 'CASHEW HONEY PRALINE', 'Peanut & Nuts Series', 5, 15, 35, '[Master Base: Nut Base] Cashew praline dan natural honey dicampurkan ke base mix saat tahap balancing untuk menghasilkan aroma madu dan kacang mete panggang.'),
  ('rcp-fruit-01', 'flv-fruit-01', 'BLUEBERRY CREAM CHEESE', 'Fruit Series', 5, 15, 35, '[Master Base: Cream Cheese / Mascarpone Base] Cream cheese diemulsikan ke base mix; puree blueberry dimasukkan setelah pendinginan atau sebagai ribbon swirl agar profil buah cerah.'),
  ('rcp-fruit-02', 'flv-fruit-02', 'AVOCADO CHOCOLOCO', 'Fruit Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Avocado puree dihomogenisasi dingin ke dalam mix yang telah diawetkan/ aging; cokelat & cocoa powder masuk saat balancing awal.'),
  ('rcp-fruit-03', 'flv-fruit-03', 'RASPBERRY MASCARPONE', 'Fruit Series', 5, 15, 35, '[Master Base: Cream Cheese / Mascarpone Base] Mascarpone diemulsikan ke dairy base; raspberry puree yang asam dicampurkan secara dingin atau diaplikasikan sebagai swirl layer.'),
  ('rcp-fruit-04', 'flv-fruit-04', 'BANANA CREAM PIE', 'Fruit Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Banana puree dihomogenisasi bersama base mix; pie/biscuit component dimasukkan sebagai crust inclusion pada tahap akhir churning.'),
  ('rcp-fruit-05', 'flv-fruit-05', 'PASSIONFRUIT VANILLA BEAN', 'Fruit Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Passionfruit puree dan vanilla bean component dipadukan secara seimbang untuk menghasilkan rasa asam segar dan aroma vanilla pekat.'),
  ('rcp-fruit-06', 'flv-fruit-06', 'PEACH & HONEY YOGURT', 'Fruit Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Yogurt segar dan madu murni dicampurkan dingin bersama peach puree ke dalam aged base untuk menjaga keasaman yogurt dan aroma madu.'),
  ('rcp-fruit-07', 'flv-fruit-07', 'AMARENA CHERRY CREAM', 'Fruit Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Amarena cherry component dimasukkan sebagian ke dalam base dan sebagian lagi diaplikasikan sebagai ripple swirl saat penarikan pan.'),
  ('rcp-fruit-08', 'flv-fruit-08', 'MANGO COCONUT CREAM', 'Fruit Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Santan kental (coconut cream) dicampur ke dairy mix saat pasteurisasi; mango puree matang dicampurkan dingin ke base sebelum churning.'),
  ('rcp-fruit-09', 'flv-fruit-09', 'STRAWBERRY LEMON SHORTCAKE', 'Fruit Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Strawberry puree & lemon component dihomogenisasi ke base; shortcake biscuit crumbs dimasukkan pada tahap akhir churning.'),
  ('rcp-dairyfree-01', 'flv-dairyfree-01', 'WILD MIXED BERRIES SORBET', 'Dairy-Free / Sorbetto Series', 4, 12, 25, '[Master Base: Fruit Sorbetto Base] Sirup gula dipasteurisasi & didinginkan; berry puree dimasukkan saat dingin (cold blend) agar aroma dan warna merah pekat tetap segar.'),
  ('rcp-dairyfree-02', 'flv-dairyfree-02', 'ALPHONSO MANGO SORBETTO', 'Dairy-Free / Sorbetto Series', 4, 12, 25, '[Master Base: Fruit Sorbetto Base] Alphonso mango puree dengan brix tinggi dihomogenisasi dingin bersama sirup gula dan acid balancer untuk tekstur dense & scoopable.'),
  ('rcp-dairyfree-03', 'flv-dairyfree-03', 'MIDNIGHT DARK COCOA SORBET', 'Dairy-Free / Sorbetto Series', 4, 12, 25, '[Master Base: Dark Cocoa Sorbetto Base] Cocoa powder dilarutkan & dipasteurisasi bersama air dan gula; serat larut mengimbangi ketiadaan lemak susu untuk mouthfeel pekat.'),
  ('rcp-dairyfree-04', 'flv-dairyfree-04', 'DRAGONFRUIT LIME PITAYA', 'Dairy-Free / Sorbetto Series', 4, 12, 25, '[Master Base: Fruit Sorbetto Base] Puree buah naga merah dicampurkan dingin bersama air perasan jeruk nipis (lime juice) untuk memberi acidity dan stabilitas warna cerah.'),
  ('rcp-dairyfree-05', 'flv-dairyfree-05', 'SICILIAN LIMONE SORBETTO', 'Dairy-Free / Sorbetto Series', 4, 12, 25, '[Master Base: Fruit Sorbetto Base] Sirup gula dimasak & didinginkan; perasan lemon segar & zest/minyak aroma lemon dimasukkan terakhir sebelum proses churning.'),
  ('rcp-dairyfree-06', 'flv-dairyfree-06', 'PASSIONFRUIT MINT FREEZE', 'Dairy-Free / Sorbetto Series', 4, 12, 25, '[Master Base: Fruit Sorbetto Base] Passionfruit puree disatukan dingin dengan ekstrak mint aromatik; menghasilkan profil asam kuat dengan sensasi dingin mint alami.'),
  ('rcp-dairyfree-07', 'flv-dairyfree-07', 'LYCHEE RASPBERRY ROSE', 'Dairy-Free / Sorbetto Series', 4, 12, 25, '[Master Base: Fruit Sorbetto Base] Puree leci manis, raspberry tart, dan rose water/component disatukan secara dingin untuk menjaga keharuman floral yang lembut.'),
  ('rcp-dairyfree-08', 'flv-dairyfree-08', 'PINEAPPLE BASIL SORBET', 'Dairy-Free / Sorbetto Series', 4, 12, 25, '[Master Base: Fruit Sorbetto Base] Nanas manis tropis di-blend dingin bersama infus basil aromatik dan sedikit citrus balancer untuk profil herba-buah menyegarkan.'),
  ('rcp-dairyfree-09', 'flv-dairyfree-09', 'WATERMELON MINT BREEZE', 'Dairy-Free / Sorbetto Series', 4, 12, 25, '[Master Base: Fruit Sorbetto Base] Semangka segar disaring & dicampur dingin bersama ekstrak mint dan perasan jeruk nipis ke dalam sirup dasar yang telah dingin.'),
  ('rcp-tea-01', 'flv-tea-01', 'KYOTO OICI MATCHA', 'Tea Series', 5, 15, 35, '[Master Base: Tea Base] Bubuk matcha murni berkualitas tinggi dicampurkan merata dengan bahan kering sebelum blending ke dalam susu untuk mencegah gumpalan.'),
  ('rcp-tea-02', 'flv-tea-02', 'EARL GREY LAVENDER MILK', 'Tea Series', 5, 15, 35, '[Master Base: Tea Base] Daun teh Earl Grey diinfusikan ke dalam susu cair; sari lavender dikontrol presisi agar aroma floral seimbang dan elegan.'),
  ('rcp-tea-03', 'flv-tea-03', 'JASMINE OOLONG PEACH', 'Tea Series', 5, 15, 35, '[Master Base: Tea Base] Teh Jasmine Oolong diekstraksi ke dalam base; puree buah peach dimasukkan saat base dingin untuk mempertahankan kesegaran aroma buah.'),
  ('rcp-tea-04', 'flv-tea-04', 'HOJICHA ROASTED GREEN TEA', 'Tea Series', 5, 15, 35, '[Master Base: Tea Base] Hojicha diekstraksi pekat melalui infusi susu untuk menghasilkan rasa roasted & nutty yang halus tanpa tekstur berpasir.'),
  ('rcp-coffee-01', 'flv-coffee-01', 'BUTTERSCOTCH SEA SALT LATTE', 'Coffee Series', 5, 15, 35, '[Master Base: Coffee Base] Espresso konsentrat dan butterscotch component dicampurkan ke base; sea salt memberikan balance gurih terhadap rasa karamel mentega.'),
  ('rcp-coffee-02', 'flv-coffee-02', 'ICED CARAMEL MACCHIATO GELATO', 'Coffee Series', 5, 15, 35, '[Master Base: Coffee Base] Base susu-kopi pekat; caramel sauce dimasukkan sebagian ke base dan sebagian diaplikasikan sebagai ribbon swirl saat dispensing.'),
  ('rcp-coffee-03', 'flv-coffee-03', 'AFFOGATO HAZELNUT SWIRL', 'Coffee Series', 5, 15, 35, '[Master Base: Coffee Base / Nut Base] Roasted hazelnut paste diemulsikan ke base kopi; chocolate/hazelnut swirl ditambahkan secara marbling saat gelato keluar dari batch freezer.'),
  ('rcp-coffee-04', 'flv-coffee-04', 'DIRTY MATCHA ESPRESSO', 'Coffee Series', 5, 15, 35, '[Master Base: Coffee Base / Tea Base] Perpaduan earthy matcha dan espresso roast; matcha dihomogenisasi ke dalam base mix dan espresso konsentrat dimasukkan post-cooling.'),
  ('rcp-seasonal-01', 'flv-seasonal-01', 'GINGERBREAD SPICE & MOLASSES', 'Seasonal Series', 5, 15, 35, '[Master Base: Dessert / Custard Base] Molasses & gingerbread spice masuk saat pasteurisasi base; remah biskuit gingerbread dimasukkan pada tahap akhir churning.'),
  ('rcp-seasonal-02', 'flv-seasonal-02', 'PEPPERMINT BARK CHOCOLATE', 'Seasonal Series', 5, 15, 35, '[Master Base: Chocolate Base] Dark chocolate & peppermint component diemulsikan ke base; flakes cokelat peppermint di-swirl saat penarikan ke dalam pan.'),
  ('rcp-seasonal-03', 'flv-seasonal-03', 'KASTENGEL CHEESE SWIRL', 'Seasonal Series', 5, 15, 35, '[Master Base: Cream Cheese / Mascarpone Base] Cream cheese & aged cheese disatukan ke base; remah kastengel keju gurih dimasukkan post-churning sebagai crunchy swirl.'),
  ('rcp-seasonal-04', 'flv-seasonal-04', 'NASTAR PINEAPPLE BUTTER', 'Seasonal Series', 5, 15, 35, '[Master Base: Dessert / Custard Base] Mentega (butter) diemulsikan hangat ke base; pineapple jam dan nastar pastry crumb diaplikasikan saat proses penarikan gelato.'),
  ('rcp-seasonal-05', 'flv-seasonal-05', 'MANDARIN ORANGE BLOSSOM', 'Seasonal Series', 5, 15, 35, '[Master Base: Fruit Sorbetto Base] Sirup gula dipasteurisasi & didinginkan; jus mandarin dan ekstrak orange blossom dimasukkan secara cold blend sebelum churning.'),
  ('rcp-seasonal-06', 'flv-seasonal-06', 'RED BEAN LOTUS PASTRY', 'Seasonal Series', 5, 15, 35, '[Master Base: Dessert / Custard Base] Pasta kacang merah halus dicampur ke dalam base susu; potongan pastry biji lotus dimasukkan sebagai inclusion pada akhir churning.'),
  ('rcp-seasonal-07', 'flv-seasonal-07', 'ES DOGER DELUXE', 'Seasonal Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Santan kental & krimer kental manis dipasteurisasi ke base; tape singkong manis & red bean dimasukkan sebagai inclusion dingin.'),
  ('rcp-seasonal-08', 'flv-seasonal-08', 'RED WHITE COCONUT STRAWBERRY', 'Seasonal Series', 5, 15, 35, '[Master Base: Fruit Milk Base] Base kelapa gurih dipadukan dengan strawberry puree dingin; swirl selai strawberry merah pekat ditambahkan saat penarikan pan.'),
  ('rcp-dessert-01', 'flv-dessert-01', 'TIRAMISU TRADIZIONALE', 'Dessert Series', 5, 15, 35, '[Master Base: Dessert / Custard Base] Mascarpone gelato base layered with espresso-soaked ladyfinger biscuits and dusted cocoa.'),
  ('rcp-dessert-02', 'flv-dessert-02', 'LOTUS BISCOFF CRUNCH', 'Dessert Series', 5, 15, 35, '[Master Base: Dessert / Custard Base] Melt Biscoff cookie butter spread into warm base. Fold coarse Biscoff cookie crumbs during final churning.'),
  ('rcp-dessert-03', 'flv-dessert-03', 'NEW YORK CHEESECAKE', 'Dessert Series', 5, 15, 35, '[Master Base: Cream Cheese / Mascarpone Base] Rich cream cheese gelato base swirled with graham cracker crust crumble and vanilla.'),
  ('rcp-dessert-04', 'flv-dessert-04', 'RED VELVET CREAM CHEESE', 'Dessert Series', 5, 15, 35, '[Master Base: Dessert / Custard Base] Cocoa infused red velvet cake gelato layered with sweet cream cheese frosting swirl.'),
  ('rcp-dessert-05', 'flv-dessert-05', 'APPLE PIE CINNAMON', 'Dessert Series', 5, 15, 35, '[Master Base: Dessert / Custard Base] Cinnamon spiced cooked apple compote swirled into sweet butter cream base with pie crust pieces.'),
  ('rcp-dessert-06', 'flv-dessert-06', 'KEY LIME PIE', 'Dessert Series', 5, 15, 35, '[Master Base: Dessert / Custard Base] Tart Florida key lime curd emulsified into sweet dairy base, folded with graham cracker crunch.'),
  ('rcp-dessert-07', 'flv-dessert-07', 'LEMON TART MERINGUE', 'Dessert Series', 5, 15, 35, '[Master Base: Dessert / Custard Base] Fresh lemon curd gelato swirled with toasted marshmallow meringue and butter tart pastry.')
ON CONFLICT (id) DO UPDATE SET instructions = EXCLUDED.instructions;

-- 2. SEED RECIPES INGREDIENTS FOR ALL 69 FLAVORS
INSERT INTO public.recipe_ingredients (recipe_id, item_id, item_name, amount, unit)
VALUES
  ('rcp-milk-01', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1851, 'gram'),
  ('rcp-milk-01', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 300, 'gram'),
  ('rcp-milk-01', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-milk-01', 'inv-sukrosa', 'Sukrosa', 375, 'gram'),
  ('rcp-milk-01', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-01', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-milk-01', 'inv-chocolate-sandwich-cookie-crumb', 'Chocolate Sandwich Cookie Crumb', 165, 'gram'),
  ('rcp-milk-01', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-milk-01', 'inv-vanilla', 'Vanilla', 6, 'gram'),
  ('rcp-milk-01', 'inv-sea-salt', 'Sea Salt', 3, 'gram'),
  ('rcp-milk-02', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1800, 'gram'),
  ('rcp-milk-02', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 315, 'gram'),
  ('rcp-milk-02', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-milk-02', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-milk-02', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-02', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-milk-02', 'inv-cream-cheese', 'Cream Cheese', 150, 'gram'),
  ('rcp-milk-02', 'inv-crispy-wafer', 'Crispy Wafer', 87, 'gram'),
  ('rcp-milk-02', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-milk-02', 'inv-sea-salt', 'Sea Salt', 3, 'gram'),
  ('rcp-milk-03', 'inv-whole-milk-3-5---infused-', 'Whole Milk 3.5% (Infused)', 1800, 'gram'),
  ('rcp-milk-03', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 300, 'gram'),
  ('rcp-milk-03', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-milk-03', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-milk-03', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-03', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-milk-03', 'inv-toasted-cereal-component', 'Toasted Cereal Component', 195, 'gram'),
  ('rcp-milk-03', 'inv-honey-crunch', 'Honey Crunch', 57, 'gram'),
  ('rcp-milk-03', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-milk-03', 'inv-sea-salt', 'Sea Salt', 3, 'gram'),
  ('rcp-milk-04', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1830, 'gram'),
  ('rcp-milk-04', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 285, 'gram'),
  ('rcp-milk-04', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-milk-04', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-milk-04', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-04', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-milk-04', 'inv-strawberry-puree', 'Strawberry Puree', 225, 'gram'),
  ('rcp-milk-04', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-milk-04', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-milk-04', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-milk-05', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-milk-05', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 315, 'gram'),
  ('rcp-milk-05', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-milk-05', 'inv-sukrosa', 'Sukrosa', 360, 'gram'),
  ('rcp-milk-05', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-05', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-milk-05', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-milk-05', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-milk-05', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-milk-05', 'inv-dark-chocolate-64-70-', 'Dark Chocolate 64–70%', 240, 'gram'),
  ('rcp-milk-06', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1800, 'gram'),
  ('rcp-milk-06', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 255, 'gram'),
  ('rcp-milk-06', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-milk-06', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-milk-06', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-06', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-milk-06', 'inv-banana-puree', 'Banana Puree', 210, 'gram'),
  ('rcp-milk-06', 'inv-nutella---hazelnut-cocoa-spread', 'Nutella / Hazelnut-Cocoa Spread', 135, 'gram'),
  ('rcp-milk-06', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-milk-07', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1815, 'gram'),
  ('rcp-milk-07', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 300, 'gram'),
  ('rcp-milk-07', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-milk-07', 'inv-sukrosa', 'Sukrosa', 360, 'gram'),
  ('rcp-milk-07', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-07', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-milk-07', 'inv-fudgy-brownie', 'Fudgy Brownie', 210, 'gram'),
  ('rcp-milk-07', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-milk-07', 'inv-vanilla', 'Vanilla', 12, 'gram'),
  ('rcp-milk-07', 'inv-sea-salt', 'Sea Salt', 3, 'gram'),
  ('rcp-milk-08', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1800, 'gram'),
  ('rcp-milk-08', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 270, 'gram'),
  ('rcp-milk-08', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-milk-08', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-milk-08', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-08', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-milk-08', 'inv-white-chocolate', 'White Chocolate', 195, 'gram'),
  ('rcp-milk-08', 'inv-crispy-wafer', 'Crispy Wafer', 105, 'gram'),
  ('rcp-milk-08', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-milk-09', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1872, 'gram'),
  ('rcp-milk-09', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 345, 'gram'),
  ('rcp-milk-09', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 150, 'gram'),
  ('rcp-milk-09', 'inv-sukrosa', 'Sukrosa', 435, 'gram'),
  ('rcp-milk-09', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-09', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 90, 'gram'),
  ('rcp-milk-09', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-milk-09', 'inv-sea-salt', 'Sea Salt', 3, 'gram'),
  ('rcp-milk-10', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1815, 'gram'),
  ('rcp-milk-10', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 330, 'gram'),
  ('rcp-milk-10', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-milk-10', 'inv-sukrosa', 'Sukrosa', 360, 'gram'),
  ('rcp-milk-10', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-milk-10', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-milk-10', 'inv-caramel-component', 'Caramel Component', 195, 'gram'),
  ('rcp-milk-10', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-01', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-choco-01', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 225, 'gram'),
  ('rcp-choco-01', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-01', 'inv-sukrosa', 'Sukrosa', 375, 'gram'),
  ('rcp-choco-01', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-choco-01', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-01', 'inv-dark-chocolate-70-75-', 'Dark Chocolate 70–75%', 240, 'gram'),
  ('rcp-choco-01', 'inv-cocoa-powder', 'Cocoa Powder', 90, 'gram'),
  ('rcp-choco-01', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-02', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1725, 'gram'),
  ('rcp-choco-02', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-choco-02', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-02', 'inv-sukrosa', 'Sukrosa', 315, 'gram'),
  ('rcp-choco-02', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-choco-02', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-02', 'inv-hazelnut-cocoa-spread', 'Hazelnut-Cocoa Spread', 225, 'gram'),
  ('rcp-choco-02', 'inv-cocoa-powder', 'Cocoa Powder', 90, 'gram'),
  ('rcp-choco-02', 'inv-roasted-hazelnut-praline', 'Roasted Hazelnut Praline', 135, 'gram'),
  ('rcp-choco-02', 'inv-crisped-wafer', 'Crisped Wafer', 15, 'gram'),
  ('rcp-choco-02', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-03', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-choco-03', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-choco-03', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-03', 'inv-sukrosa', 'Sukrosa', 375, 'gram'),
  ('rcp-choco-03', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-choco-03', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-03', 'inv-cocoa-powder', 'Cocoa Powder', 165, 'gram'),
  ('rcp-choco-03', 'inv-dark-chocolate--flakes-', 'Dark Chocolate (Flakes)', 135, 'gram'),
  ('rcp-choco-03', 'inv-mint-infusion---component', 'Mint Infusion / Component', 15, 'gram'),
  ('rcp-choco-03', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-04', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-choco-04', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 225, 'gram'),
  ('rcp-choco-04', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-04', 'inv-sukrosa', 'Sukrosa', 360, 'gram'),
  ('rcp-choco-04', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-choco-04', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-04', 'inv-cocoa-powder', 'Cocoa Powder', 150, 'gram'),
  ('rcp-choco-04', 'inv-dark-chocolate', 'Dark Chocolate', 165, 'gram'),
  ('rcp-choco-04', 'inv-fudgy-brownie-chunk', 'Fudgy Brownie Chunk', 30, 'gram'),
  ('rcp-choco-04', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-05', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-choco-05', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-choco-05', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-05', 'inv-sukrosa', 'Sukrosa', 315, 'gram'),
  ('rcp-choco-05', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-choco-05', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-05', 'inv-white-chocolate', 'White Chocolate', 240, 'gram'),
  ('rcp-choco-05', 'inv-berry-puree---swirl', 'Berry Puree / Swirl', 135, 'gram'),
  ('rcp-choco-05', 'inv-sea-salt', 'Sea Salt', 15, 'gram'),
  ('rcp-choco-05', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-06', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1761, 'gram'),
  ('rcp-choco-06', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 222, 'gram'),
  ('rcp-choco-06', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-06', 'inv-sukrosa', 'Sukrosa', 360, 'gram'),
  ('rcp-choco-06', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-choco-06', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-06', 'inv-cocoa-powder', 'Cocoa Powder', 165, 'gram'),
  ('rcp-choco-06', 'inv-dark-chocolate', 'Dark Chocolate', 165, 'gram'),
  ('rcp-choco-06', 'inv-candied-orange-peel', 'Candied Orange Peel', 30, 'gram'),
  ('rcp-choco-06', 'inv-orange-component---zest', 'Orange Component / Zest', 9, 'gram'),
  ('rcp-choco-06', 'inv-sea-salt', 'Sea Salt', 3, 'gram'),
  ('rcp-choco-06', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-07', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1740, 'gram'),
  ('rcp-choco-07', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 225, 'gram'),
  ('rcp-choco-07', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-07', 'inv-sukrosa', 'Sukrosa', 315, 'gram'),
  ('rcp-choco-07', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-choco-07', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-07', 'inv-cocoa-powder', 'Cocoa Powder', 150, 'gram'),
  ('rcp-choco-07', 'inv-dark-chocolate', 'Dark Chocolate', 165, 'gram'),
  ('rcp-choco-07', 'inv-caramel-component', 'Caramel Component', 120, 'gram'),
  ('rcp-choco-07', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-08', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-choco-08', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-choco-08', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-08', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-choco-08', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-choco-08', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-08', 'inv-belgian-milk-chocolate', 'Belgian Milk Chocolate', 390, 'gram'),
  ('rcp-choco-08', 'inv-cocoa-powder', 'Cocoa Powder', 15, 'gram'),
  ('rcp-choco-08', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-09', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1755, 'gram'),
  ('rcp-choco-09', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-choco-09', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-09', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-choco-09', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-choco-09', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-09', 'inv-cocoa-powder', 'Cocoa Powder', 240, 'gram'),
  ('rcp-choco-09', 'inv-dark-chocolate', 'Dark Chocolate', 165, 'gram'),
  ('rcp-choco-09', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-choco-10', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1755, 'gram'),
  ('rcp-choco-10', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 225, 'gram'),
  ('rcp-choco-10', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-choco-10', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-choco-10', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-choco-10', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-choco-10', 'inv-cocoa-powder', 'Cocoa Powder', 165, 'gram'),
  ('rcp-choco-10', 'inv-dark---milk-chocolate', 'Dark / Milk Chocolate', 165, 'gram'),
  ('rcp-choco-10', 'inv-marshmallow-component', 'Marshmallow Component', 60, 'gram'),
  ('rcp-choco-10', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-nuts-01', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1860, 'gram'),
  ('rcp-nuts-01', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 195, 'gram'),
  ('rcp-nuts-01', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-nuts-01', 'inv-pistachio-bronte-paste', 'Pistachio Bronte Paste', 240, 'gram'),
  ('rcp-nuts-01', 'inv-sukrosa', 'Sukrosa', 375, 'gram'),
  ('rcp-nuts-01', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-nuts-01', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-nuts-01', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-nuts-01', 'inv-sea-salt', 'Sea Salt', 3, 'gram'),
  ('rcp-nuts-01', 'inv-vanilla', 'Vanilla', 12, 'gram'),
  ('rcp-nuts-02', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1860, 'gram'),
  ('rcp-nuts-02', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 195, 'gram'),
  ('rcp-nuts-02', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-nuts-02', 'inv-hazelnut-piemonte-paste', 'Hazelnut Piemonte Paste', 240, 'gram'),
  ('rcp-nuts-02', 'inv-sukrosa', 'Sukrosa', 375, 'gram'),
  ('rcp-nuts-02', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-nuts-02', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-nuts-02', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-nuts-02', 'inv-sea-salt', 'Sea Salt', 3, 'gram'),
  ('rcp-nuts-02', 'inv-vanilla', 'Vanilla', 12, 'gram'),
  ('rcp-nuts-03', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1830, 'gram'),
  ('rcp-nuts-03', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 195, 'gram'),
  ('rcp-nuts-03', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-nuts-03', 'inv-peanut-butter', 'Peanut Butter', 225, 'gram'),
  ('rcp-nuts-03', 'inv-sukrosa', 'Sukrosa', 360, 'gram'),
  ('rcp-nuts-03', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-nuts-03', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-nuts-03', 'inv-peanut-crisp-component', 'Peanut Crisp Component', 60, 'gram'),
  ('rcp-nuts-03', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-nuts-03', 'inv-sea-salt', 'Sea Salt', 9, 'gram'),
  ('rcp-nuts-03', 'inv-vanilla', 'Vanilla', 6, 'gram'),
  ('rcp-nuts-04', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1815, 'gram'),
  ('rcp-nuts-04', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-nuts-04', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-nuts-04', 'inv-almond-butter---paste', 'Almond Butter / Paste', 225, 'gram'),
  ('rcp-nuts-04', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-nuts-04', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-nuts-04', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-nuts-04', 'inv-caramel-component', 'Caramel Component', 90, 'gram'),
  ('rcp-nuts-04', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-nuts-04', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-nuts-04', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-nuts-05', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1860, 'gram'),
  ('rcp-nuts-05', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 195, 'gram'),
  ('rcp-nuts-05', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-nuts-05', 'inv-black-sesame-paste', 'Black Sesame Paste', 225, 'gram'),
  ('rcp-nuts-05', 'inv-sukrosa', 'Sukrosa', 375, 'gram'),
  ('rcp-nuts-05', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-nuts-05', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-nuts-05', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-nuts-05', 'inv-sea-salt', 'Sea Salt', 9, 'gram'),
  ('rcp-nuts-05', 'inv-vanilla', 'Vanilla', 21, 'gram'),
  ('rcp-nuts-06', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1845, 'gram'),
  ('rcp-nuts-06', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 195, 'gram'),
  ('rcp-nuts-06', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-nuts-06', 'inv-pecan-paste', 'Pecan Paste', 195, 'gram'),
  ('rcp-nuts-06', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-nuts-06', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-nuts-06', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-nuts-06', 'inv-maple-crunch-component', 'Maple Crunch Component', 90, 'gram'),
  ('rcp-nuts-06', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-nuts-06', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-nuts-06', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-nuts-07', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1800, 'gram'),
  ('rcp-nuts-07', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 195, 'gram'),
  ('rcp-nuts-07', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-nuts-07', 'inv-macadamia-paste', 'Macadamia Paste', 195, 'gram'),
  ('rcp-nuts-07', 'inv-white-chocolate', 'White Chocolate', 210, 'gram'),
  ('rcp-nuts-07', 'inv-sukrosa', 'Sukrosa', 315, 'gram'),
  ('rcp-nuts-07', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-nuts-07', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-nuts-07', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-nuts-07', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-nuts-07', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-nuts-08', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1830, 'gram'),
  ('rcp-nuts-08', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 195, 'gram'),
  ('rcp-nuts-08', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-nuts-08', 'inv-cashew-praline-component', 'Cashew Praline Component', 240, 'gram'),
  ('rcp-nuts-08', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-nuts-08', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-nuts-08', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-nuts-08', 'inv-honey--madu-murni-', 'Honey (Madu Murni)', 60, 'gram'),
  ('rcp-nuts-08', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-nuts-08', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-nuts-08', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-fruit-01', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1785, 'gram'),
  ('rcp-fruit-01', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 225, 'gram'),
  ('rcp-fruit-01', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-fruit-01', 'inv-cream-cheese', 'Cream Cheese', 150, 'gram'),
  ('rcp-fruit-01', 'inv-blueberry-puree', 'Blueberry Puree', 225, 'gram'),
  ('rcp-fruit-01', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-fruit-01', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-fruit-01', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-fruit-01', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-fruit-01', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-fruit-01', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-fruit-02', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1725, 'gram'),
  ('rcp-fruit-02', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 195, 'gram'),
  ('rcp-fruit-02', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-fruit-02', 'inv-avocado-puree', 'Avocado Puree', 300, 'gram'),
  ('rcp-fruit-02', 'inv-cocoa-powder', 'Cocoa Powder', 105, 'gram'),
  ('rcp-fruit-02', 'inv-dark-chocolate', 'Dark Chocolate', 90, 'gram'),
  ('rcp-fruit-02', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-fruit-02', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-fruit-02', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-fruit-02', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-fruit-02', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-fruit-02', 'inv-vanilla-component', 'Vanilla Component', 69, 'gram'),
  ('rcp-fruit-03', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1785, 'gram'),
  ('rcp-fruit-03', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-fruit-03', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-fruit-03', 'inv-mascarpone', 'Mascarpone', 150, 'gram'),
  ('rcp-fruit-03', 'inv-raspberry-puree', 'Raspberry Puree', 240, 'gram'),
  ('rcp-fruit-03', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-fruit-03', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-fruit-03', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-fruit-03', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-fruit-03', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-fruit-03', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-fruit-04', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-fruit-04', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-fruit-04', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-fruit-04', 'inv-banana-puree', 'Banana Puree', 240, 'gram'),
  ('rcp-fruit-04', 'inv-pie---biscuit-component', 'Pie / Biscuit Component', 150, 'gram'),
  ('rcp-fruit-04', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-fruit-04', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-fruit-04', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-fruit-04', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-fruit-04', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-fruit-04', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-fruit-05', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1800, 'gram'),
  ('rcp-fruit-05', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-fruit-05', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-fruit-05', 'inv-passionfruit-puree', 'Passionfruit Puree', 270, 'gram'),
  ('rcp-fruit-05', 'inv-sukrosa', 'Sukrosa', 360, 'gram'),
  ('rcp-fruit-05', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-fruit-05', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-fruit-05', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-fruit-05', 'inv-vanilla-bean-component', 'Vanilla Bean Component', 60, 'gram'),
  ('rcp-fruit-05', 'inv-vanilla-extract', 'Vanilla Extract', 9, 'gram'),
  ('rcp-fruit-05', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-fruit-06', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1710, 'gram'),
  ('rcp-fruit-06', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 195, 'gram'),
  ('rcp-fruit-06', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-fruit-06', 'inv-yogurt', 'Yogurt', 180, 'gram'),
  ('rcp-fruit-06', 'inv-peach-puree', 'Peach Puree', 225, 'gram'),
  ('rcp-fruit-06', 'inv-honey--madu-murni-', 'Honey (Madu Murni)', 75, 'gram'),
  ('rcp-fruit-06', 'inv-sukrosa', 'Sukrosa', 315, 'gram'),
  ('rcp-fruit-06', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-fruit-06', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-fruit-06', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-fruit-06', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-fruit-06', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-fruit-07', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1800, 'gram'),
  ('rcp-fruit-07', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-fruit-07', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-fruit-07', 'inv-amarena-cherry-component', 'Amarena Cherry Component', 345, 'gram'),
  ('rcp-fruit-07', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-fruit-07', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-fruit-07', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-fruit-07', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-fruit-07', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-fruit-07', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-fruit-08', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1680, 'gram'),
  ('rcp-fruit-08', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 165, 'gram'),
  ('rcp-fruit-08', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-fruit-08', 'inv-mango-puree', 'Mango Puree', 360, 'gram'),
  ('rcp-fruit-08', 'inv-coconut-cream---milk', 'Coconut Cream / Milk', 180, 'gram'),
  ('rcp-fruit-08', 'inv-sukrosa', 'Sukrosa', 315, 'gram'),
  ('rcp-fruit-08', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-fruit-08', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-fruit-08', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-fruit-08', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-fruit-08', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-fruit-09', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1755, 'gram'),
  ('rcp-fruit-09', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-fruit-09', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-fruit-09', 'inv-strawberry-puree', 'Strawberry Puree', 240, 'gram'),
  ('rcp-fruit-09', 'inv-lemon-component', 'Lemon Component', 45, 'gram'),
  ('rcp-fruit-09', 'inv-shortcake---biscuit-component', 'Shortcake / Biscuit Component', 120, 'gram'),
  ('rcp-fruit-09', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-fruit-09', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-fruit-09', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 45, 'gram'),
  ('rcp-fruit-09', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-fruit-09', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-fruit-09', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-dairyfree-01', 'inv-mixed-berry-puree', 'Mixed Berry Puree', 1375, 'gram'),
  ('rcp-dairyfree-01', 'inv-water', 'Water', 550, 'gram'),
  ('rcp-dairyfree-01', 'inv-sukrosa', 'Sukrosa', 300, 'gram'),
  ('rcp-dairyfree-01', 'inv-dextrose', 'Dextrose', 125, 'gram'),
  ('rcp-dairyfree-01', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 87.5, 'gram'),
  ('rcp-dairyfree-01', 'inv-invert-sugar', 'Invert Sugar', 37.5, 'gram'),
  ('rcp-dairyfree-01', 'inv-soluble-fiber', 'Soluble Fiber', 12.5, 'gram'),
  ('rcp-dairyfree-01', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 10, 'gram'),
  ('rcp-dairyfree-01', 'inv-lemon-juice---acid-component', 'Lemon Juice / Acid Component', 2.5, 'gram'),
  ('rcp-dairyfree-02', 'inv-alphonso-mango-puree', 'Alphonso Mango Puree', 1500, 'gram'),
  ('rcp-dairyfree-02', 'inv-water', 'Water', 425, 'gram'),
  ('rcp-dairyfree-02', 'inv-sukrosa', 'Sukrosa', 287.5, 'gram'),
  ('rcp-dairyfree-02', 'inv-dextrose', 'Dextrose', 125, 'gram'),
  ('rcp-dairyfree-02', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 87.5, 'gram'),
  ('rcp-dairyfree-02', 'inv-invert-sugar', 'Invert Sugar', 50, 'gram'),
  ('rcp-dairyfree-02', 'inv-soluble-fiber', 'Soluble Fiber', 12.5, 'gram'),
  ('rcp-dairyfree-02', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 10, 'gram'),
  ('rcp-dairyfree-02', 'inv-lemon-juice---acid-component', 'Lemon Juice / Acid Component', 2.5, 'gram'),
  ('rcp-dairyfree-03', 'inv-water', 'Water', 1425, 'gram'),
  ('rcp-dairyfree-03', 'inv-cocoa-powder--pure-dark-', 'Cocoa Powder (Pure Dark)', 225, 'gram'),
  ('rcp-dairyfree-03', 'inv-sukrosa', 'Sukrosa', 437.5, 'gram'),
  ('rcp-dairyfree-03', 'inv-dextrose', 'Dextrose', 137.5, 'gram'),
  ('rcp-dairyfree-03', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 100, 'gram'),
  ('rcp-dairyfree-03', 'inv-invert-sugar', 'Invert Sugar', 87.5, 'gram'),
  ('rcp-dairyfree-03', 'inv-soluble-fiber---cocoa-solids', 'Soluble Fiber / Cocoa Solids', 75, 'gram'),
  ('rcp-dairyfree-03', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 12.5, 'gram'),
  ('rcp-dairyfree-04', 'inv-dragonfruit---pitaya-puree', 'Dragonfruit / Pitaya Puree', 1375, 'gram'),
  ('rcp-dairyfree-04', 'inv-water', 'Water', 550, 'gram'),
  ('rcp-dairyfree-04', 'inv-sukrosa', 'Sukrosa', 300, 'gram'),
  ('rcp-dairyfree-04', 'inv-dextrose', 'Dextrose', 125, 'gram'),
  ('rcp-dairyfree-04', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 87.5, 'gram'),
  ('rcp-dairyfree-04', 'inv-invert-sugar', 'Invert Sugar', 25, 'gram'),
  ('rcp-dairyfree-04', 'inv-soluble-fiber', 'Soluble Fiber', 12.5, 'gram'),
  ('rcp-dairyfree-04', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 10, 'gram'),
  ('rcp-dairyfree-04', 'inv-lime-juice', 'Lime Juice', 15, 'gram'),
  ('rcp-dairyfree-05', 'inv-water', 'Water', 1700, 'gram'),
  ('rcp-dairyfree-05', 'inv-lemon-juice', 'Lemon Juice', 375, 'gram'),
  ('rcp-dairyfree-05', 'inv-sukrosa', 'Sukrosa', 275, 'gram'),
  ('rcp-dairyfree-05', 'inv-dextrose', 'Dextrose', 75, 'gram'),
  ('rcp-dairyfree-05', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 50, 'gram'),
  ('rcp-dairyfree-05', 'inv-invert-sugar', 'Invert Sugar', 12.5, 'gram'),
  ('rcp-dairyfree-05', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 10, 'gram'),
  ('rcp-dairyfree-05', 'inv-lemon-zest---aroma-component', 'Lemon Zest / Aroma Component', 2.5, 'gram'),
  ('rcp-dairyfree-06', 'inv-passionfruit-puree', 'Passionfruit Puree', 875, 'gram'),
  ('rcp-dairyfree-06', 'inv-water', 'Water', 1025, 'gram'),
  ('rcp-dairyfree-06', 'inv-sukrosa', 'Sukrosa', 350, 'gram'),
  ('rcp-dairyfree-06', 'inv-dextrose', 'Dextrose', 125, 'gram'),
  ('rcp-dairyfree-06', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 75, 'gram'),
  ('rcp-dairyfree-06', 'inv-invert-sugar', 'Invert Sugar', 25, 'gram'),
  ('rcp-dairyfree-06', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 10, 'gram'),
  ('rcp-dairyfree-06', 'inv-mint-component', 'Mint Component', 12.5, 'gram'),
  ('rcp-dairyfree-06', 'inv-lemon---lime-juice', 'Lemon / Lime Juice', 2.5, 'gram'),
  ('rcp-dairyfree-07', 'inv-lychee-puree', 'Lychee Puree', 875, 'gram'),
  ('rcp-dairyfree-07', 'inv-raspberry-puree', 'Raspberry Puree', 500, 'gram'),
  ('rcp-dairyfree-07', 'inv-water', 'Water', 625, 'gram'),
  ('rcp-dairyfree-07', 'inv-sukrosa', 'Sukrosa', 325, 'gram'),
  ('rcp-dairyfree-07', 'inv-dextrose', 'Dextrose', 100, 'gram'),
  ('rcp-dairyfree-07', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 50, 'gram'),
  ('rcp-dairyfree-07', 'inv-invert-sugar', 'Invert Sugar', 12.5, 'gram'),
  ('rcp-dairyfree-07', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 10, 'gram'),
  ('rcp-dairyfree-07', 'inv-rose-component', 'Rose Component', 2.5, 'gram'),
  ('rcp-dairyfree-08', 'inv-pineapple-puree---juice', 'Pineapple Puree / Juice', 1300, 'gram'),
  ('rcp-dairyfree-08', 'inv-water', 'Water', 625, 'gram'),
  ('rcp-dairyfree-08', 'inv-sukrosa', 'Sukrosa', 325, 'gram'),
  ('rcp-dairyfree-08', 'inv-dextrose', 'Dextrose', 125, 'gram'),
  ('rcp-dairyfree-08', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 75, 'gram'),
  ('rcp-dairyfree-08', 'inv-invert-sugar', 'Invert Sugar', 25, 'gram'),
  ('rcp-dairyfree-08', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 10, 'gram'),
  ('rcp-dairyfree-08', 'inv-basil-component', 'Basil Component', 12.5, 'gram'),
  ('rcp-dairyfree-08', 'inv-lemon---lime-component', 'Lemon / Lime Component', 2.5, 'gram'),
  ('rcp-dairyfree-09', 'inv-watermelon-puree---juice', 'Watermelon Puree / Juice', 1500, 'gram'),
  ('rcp-dairyfree-09', 'inv-water', 'Water', 475, 'gram'),
  ('rcp-dairyfree-09', 'inv-sukrosa', 'Sukrosa', 312.5, 'gram'),
  ('rcp-dairyfree-09', 'inv-dextrose', 'Dextrose', 112.5, 'gram'),
  ('rcp-dairyfree-09', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 62.5, 'gram'),
  ('rcp-dairyfree-09', 'inv-invert-sugar', 'Invert Sugar', 12.5, 'gram'),
  ('rcp-dairyfree-09', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 10, 'gram'),
  ('rcp-dairyfree-09', 'inv-mint-component', 'Mint Component', 12.5, 'gram'),
  ('rcp-dairyfree-09', 'inv-lime-component', 'Lime Component', 2.5, 'gram'),
  ('rcp-tea-01', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1875, 'gram'),
  ('rcp-tea-01', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-tea-01', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-tea-01', 'inv-sukrosa', 'Sukrosa', 375, 'gram'),
  ('rcp-tea-01', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-tea-01', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-tea-01', 'inv-matcha-component', 'Matcha Component', 180, 'gram'),
  ('rcp-tea-01', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-tea-01', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-tea-01', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-tea-02', 'inv-whole-milk-3-5---infused-', 'Whole Milk 3.5% (Infused)', 1920, 'gram'),
  ('rcp-tea-02', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 270, 'gram'),
  ('rcp-tea-02', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-tea-02', 'inv-sukrosa', 'Sukrosa', 435, 'gram'),
  ('rcp-tea-02', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-tea-02', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-tea-02', 'inv-earl-grey-tea-component', 'Earl Grey Tea Component', 60, 'gram'),
  ('rcp-tea-02', 'inv-lavender-component', 'Lavender Component', 9, 'gram'),
  ('rcp-tea-02', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-tea-02', 'inv-vanilla', 'Vanilla', 15, 'gram'),
  ('rcp-tea-02', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-tea-03', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1830, 'gram'),
  ('rcp-tea-03', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-tea-03', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-tea-03', 'inv-peach-puree', 'Peach Puree', 180, 'gram'),
  ('rcp-tea-03', 'inv-sukrosa', 'Sukrosa', 390, 'gram'),
  ('rcp-tea-03', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-tea-03', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-tea-03', 'inv-jasmine-oolong-tea-component', 'Jasmine Oolong Tea Component', 45, 'gram'),
  ('rcp-tea-03', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-tea-03', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-tea-03', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-tea-04', 'inv-whole-milk-3-5---infused-', 'Whole Milk 3.5% (Infused)', 1890, 'gram'),
  ('rcp-tea-04', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 255, 'gram'),
  ('rcp-tea-04', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-tea-04', 'inv-sukrosa', 'Sukrosa', 420, 'gram'),
  ('rcp-tea-04', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-tea-04', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-tea-04', 'inv-hojicha-tea-component', 'Hojicha Tea Component', 120, 'gram'),
  ('rcp-tea-04', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-tea-04', 'inv-vanilla', 'Vanilla', 24, 'gram'),
  ('rcp-tea-04', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-coffee-01', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1830, 'gram'),
  ('rcp-coffee-01', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-coffee-01', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-coffee-01', 'inv-sukrosa', 'Sukrosa', 300, 'gram'),
  ('rcp-coffee-01', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-coffee-01', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-coffee-01', 'inv-butterscotch-component', 'Butterscotch Component', 150, 'gram'),
  ('rcp-coffee-01', 'inv-espresso-component', 'Espresso Component', 150, 'gram'),
  ('rcp-coffee-01', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-coffee-01', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-coffee-01', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-coffee-02', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1845, 'gram'),
  ('rcp-coffee-02', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-coffee-02', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-coffee-02', 'inv-sukrosa', 'Sukrosa', 315, 'gram'),
  ('rcp-coffee-02', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-coffee-02', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-coffee-02', 'inv-caramel-sauce---component', 'Caramel Sauce / Component', 150, 'gram'),
  ('rcp-coffee-02', 'inv-espresso-component', 'Espresso Component', 120, 'gram'),
  ('rcp-coffee-02', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-coffee-02', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-coffee-02', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-coffee-03', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1740, 'gram'),
  ('rcp-coffee-03', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-coffee-03', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-coffee-03', 'inv-hazelnut-paste', 'Hazelnut Paste', 210, 'gram'),
  ('rcp-coffee-03', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-coffee-03', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-coffee-03', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-coffee-03', 'inv-espresso-component', 'Espresso Component', 120, 'gram'),
  ('rcp-coffee-03', 'inv-hazelnut---chocolate-swirl', 'Hazelnut / Chocolate Swirl', 39, 'gram'),
  ('rcp-coffee-03', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-coffee-03', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-coffee-04', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1815, 'gram'),
  ('rcp-coffee-04', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-coffee-04', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-coffee-04', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-coffee-04', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-coffee-04', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-coffee-04', 'inv-espresso-component', 'Espresso Component', 120, 'gram'),
  ('rcp-coffee-04', 'inv-matcha-component', 'Matcha Component', 150, 'gram'),
  ('rcp-coffee-04', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-coffee-04', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-coffee-04', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-seasonal-01', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1830, 'gram'),
  ('rcp-seasonal-01', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-seasonal-01', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-seasonal-01', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-seasonal-01', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-seasonal-01', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-seasonal-01', 'inv-molasses', 'Molasses', 90, 'gram'),
  ('rcp-seasonal-01', 'inv-gingerbread-spice-component', 'Gingerbread Spice Component', 45, 'gram'),
  ('rcp-seasonal-01', 'inv-gingerbread-biscuit-component', 'Gingerbread Biscuit Component', 150, 'gram'),
  ('rcp-seasonal-01', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-seasonal-01', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-seasonal-01', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-seasonal-02', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1815, 'gram'),
  ('rcp-seasonal-02', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-seasonal-02', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-seasonal-02', 'inv-cocoa-powder', 'Cocoa Powder', 105, 'gram'),
  ('rcp-seasonal-02', 'inv-dark-chocolate--bark---flakes-', 'Dark Chocolate (Bark / Flakes)', 120, 'gram'),
  ('rcp-seasonal-02', 'inv-sukrosa', 'Sukrosa', 360, 'gram'),
  ('rcp-seasonal-02', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-seasonal-02', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-seasonal-02', 'inv-peppermint-component', 'Peppermint Component', 30, 'gram'),
  ('rcp-seasonal-02', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-seasonal-02', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-seasonal-02', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-seasonal-03', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1755, 'gram'),
  ('rcp-seasonal-03', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-seasonal-03', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-seasonal-03', 'inv-cream-cheese', 'Cream Cheese', 150, 'gram'),
  ('rcp-seasonal-03', 'inv-aged-cheese-component', 'Aged Cheese Component', 60, 'gram'),
  ('rcp-seasonal-03', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-seasonal-03', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-seasonal-03', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-seasonal-03', 'inv-kastengel-crumb---swirl', 'Kastengel Crumb / Swirl', 180, 'gram'),
  ('rcp-seasonal-03', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-seasonal-03', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-seasonal-03', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-seasonal-04', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-seasonal-04', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-seasonal-04', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 135, 'gram'),
  ('rcp-seasonal-04', 'inv-pineapple-jam-component', 'Pineapple Jam Component', 210, 'gram'),
  ('rcp-seasonal-04', 'inv-butter--mentega-murni-', 'Butter (Mentega Murni)', 75, 'gram'),
  ('rcp-seasonal-04', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-seasonal-04', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-seasonal-04', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-seasonal-04', 'inv-nastar-crumb-component', 'Nastar Crumb Component', 75, 'gram'),
  ('rcp-seasonal-04', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-seasonal-04', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-seasonal-04', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-seasonal-05', 'inv-mandarin-puree---juice', 'Mandarin Puree / Juice', 1125, 'gram'),
  ('rcp-seasonal-05', 'inv-water', 'Water', 800, 'gram'),
  ('rcp-seasonal-05', 'inv-sukrosa', 'Sukrosa', 325, 'gram'),
  ('rcp-seasonal-05', 'inv-dextrose', 'Dextrose', 125, 'gram'),
  ('rcp-seasonal-05', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 75, 'gram'),
  ('rcp-seasonal-05', 'inv-invert-sugar', 'Invert Sugar', 25, 'gram'),
  ('rcp-seasonal-05', 'inv-sorbet-stabilizer', 'Sorbet Stabilizer', 10, 'gram'),
  ('rcp-seasonal-05', 'inv-orange-blossom-component', 'Orange Blossom Component', 12.5, 'gram'),
  ('rcp-seasonal-05', 'inv-citrus-acid-component', 'Citrus Acid Component', 2.5, 'gram'),
  ('rcp-seasonal-06', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1710, 'gram'),
  ('rcp-seasonal-06', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 210, 'gram'),
  ('rcp-seasonal-06', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-seasonal-06', 'inv-red-bean-paste', 'Red Bean Paste', 300, 'gram'),
  ('rcp-seasonal-06', 'inv-lotus-pastry-component', 'Lotus Pastry Component', 150, 'gram'),
  ('rcp-seasonal-06', 'inv-sukrosa', 'Sukrosa', 300, 'gram'),
  ('rcp-seasonal-06', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-seasonal-06', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-seasonal-06', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-seasonal-06', 'inv-sea-salt', 'Sea Salt', 15, 'gram'),
  ('rcp-seasonal-06', 'inv-vanilla', 'Vanilla', 15, 'gram'),
  ('rcp-seasonal-07', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1575, 'gram'),
  ('rcp-seasonal-07', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 150, 'gram'),
  ('rcp-seasonal-07', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-seasonal-07', 'inv-coconut-milk--santan-kental-', 'Coconut Milk (Santan Kental)', 240, 'gram'),
  ('rcp-seasonal-07', 'inv-condensed-milk-component', 'Condensed Milk Component', 180, 'gram'),
  ('rcp-seasonal-07', 'inv-sukrosa', 'Sukrosa', 300, 'gram'),
  ('rcp-seasonal-07', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-seasonal-07', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-seasonal-07', 'inv-red-bean-component', 'Red Bean Component', 120, 'gram'),
  ('rcp-seasonal-07', 'inv-fermented-cassava---tape', 'Fermented Cassava / Tape', 120, 'gram'),
  ('rcp-seasonal-07', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-seasonal-07', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-seasonal-07', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-seasonal-08', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1635, 'gram'),
  ('rcp-seasonal-08', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 180, 'gram'),
  ('rcp-seasonal-08', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-seasonal-08', 'inv-strawberry-puree', 'Strawberry Puree', 300, 'gram'),
  ('rcp-seasonal-08', 'inv-coconut-cream', 'Coconut Cream', 210, 'gram'),
  ('rcp-seasonal-08', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-seasonal-08', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-seasonal-08', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-seasonal-08', 'inv-strawberry-swirl', 'Strawberry Swirl', 15, 'gram'),
  ('rcp-seasonal-08', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-seasonal-08', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-seasonal-08', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-dessert-01', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-dessert-01', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-dessert-01', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-dessert-01', 'inv-mascarpone', 'Mascarpone', 150, 'gram'),
  ('rcp-dessert-01', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-dessert-01', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-dessert-01', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-dessert-01', 'inv-espresso-component', 'Espresso Component', 120, 'gram'),
  ('rcp-dessert-01', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-dessert-01', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-dessert-01', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-dessert-02', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-dessert-02', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-dessert-02', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-dessert-02', 'inv-lotus-biscoff-spread', 'Lotus Biscoff Spread', 210, 'gram'),
  ('rcp-dessert-02', 'inv-lotus-biscoff-crumb', 'Lotus Biscoff Crumb', 90, 'gram'),
  ('rcp-dessert-02', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-dessert-02', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-dessert-02', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-dessert-02', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-dessert-02', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-dessert-03', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1785, 'gram'),
  ('rcp-dessert-03', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 225, 'gram'),
  ('rcp-dessert-03', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-dessert-03', 'inv-cream-cheese', 'Cream Cheese', 180, 'gram'),
  ('rcp-dessert-03', 'inv-graham-cracker-crumb', 'Graham Cracker Crumb', 120, 'gram'),
  ('rcp-dessert-03', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-dessert-03', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-dessert-03', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-dessert-03', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-dessert-03', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-dessert-03', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-dessert-04', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-dessert-04', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-dessert-04', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-dessert-04', 'inv-cream-cheese', 'Cream Cheese', 150, 'gram'),
  ('rcp-dessert-04', 'inv-cocoa-powder', 'Cocoa Powder', 60, 'gram'),
  ('rcp-dessert-04', 'inv-red-velvet-cake-crumb', 'Red Velvet Cake Crumb', 120, 'gram'),
  ('rcp-dessert-04', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-dessert-04', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-dessert-04', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-dessert-04', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-dessert-04', 'inv-vanilla', 'Vanilla', 9, 'gram'),
  ('rcp-dessert-05', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1800, 'gram'),
  ('rcp-dessert-05', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 255, 'gram'),
  ('rcp-dessert-05', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-dessert-05', 'inv-apple-compote-component', 'Apple Compote Component', 210, 'gram'),
  ('rcp-dessert-05', 'inv-pie-crust-crumb', 'Pie Crust Crumb', 90, 'gram'),
  ('rcp-dessert-05', 'inv-sukrosa', 'Sukrosa', 330, 'gram'),
  ('rcp-dessert-05', 'inv-dextrose', 'Dextrose', 90, 'gram'),
  ('rcp-dessert-05', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-dessert-05', 'inv-cinnamon-powder', 'Cinnamon Powder', 15, 'gram'),
  ('rcp-dessert-05', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-dessert-05', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-dessert-06', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1785, 'gram'),
  ('rcp-dessert-06', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-dessert-06', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-dessert-06', 'inv-key-lime-juice-component', 'Key Lime Juice Component', 180, 'gram'),
  ('rcp-dessert-06', 'inv-graham-cracker-crumb', 'Graham Cracker Crumb', 105, 'gram'),
  ('rcp-dessert-06', 'inv-sukrosa', 'Sukrosa', 360, 'gram'),
  ('rcp-dessert-06', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-dessert-06', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-dessert-06', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-dessert-06', 'inv-sea-salt', 'Sea Salt', 6, 'gram'),
  ('rcp-dessert-07', 'inv-whole-milk-3-5-', 'Whole Milk 3.5%', 1770, 'gram'),
  ('rcp-dessert-07', 'inv-dairy-cream-35-', 'Dairy Cream 35%', 240, 'gram'),
  ('rcp-dessert-07', 'inv-skim-milk-powder--smp-', 'Skim Milk Powder (SMP)', 120, 'gram'),
  ('rcp-dessert-07', 'inv-lemon-curd-component', 'Lemon Curd Component', 180, 'gram'),
  ('rcp-dessert-07', 'inv-marshmallow-meringue-swirl', 'Marshmallow Meringue Swirl', 105, 'gram'),
  ('rcp-dessert-07', 'inv-tart-pastry-crumb', 'Tart Pastry Crumb', 90, 'gram'),
  ('rcp-dessert-07', 'inv-sukrosa', 'Sukrosa', 345, 'gram'),
  ('rcp-dessert-07', 'inv-dextrose', 'Dextrose', 105, 'gram'),
  ('rcp-dessert-07', 'inv-glucose-powder-de40', 'Glucose Powder DE40', 60, 'gram'),
  ('rcp-dessert-07', 'inv-base-5', 'Base 5', 15, 'gram'),
  ('rcp-dessert-07', 'inv-sea-salt', 'Sea Salt', 6, 'gram');
